### ISSUE TITLE
[cc]历史会话列表-第七列-服务时间改为服务时长

### ISSUE THREAD

**Issue by wq11123** [chatopera/cosin#10]
# 描述

## 现在行为

![](https://user-images.githubusercontent.com/40993206/44890273-28c4d080-ad0c-11e8-9505-ac0f2d4cdf04.png)

## 预期行为

# 解决方案

# 环境

* 代码版本:
The commit hash (`git rev-parse HEAD`)

**Comment by xianliwang** [comment]
@Samurais 企业版没有这个问题

**Comment by xianliwang** [comment]
![image](https://user-images.githubusercontent.com/52594347/72601367-3e15bb80-3950-11ea-833a-2bb0e3885b4f.png)
