### ISSUE TITLE
[cc]历史会话点击任意访客，访问/咨询时间，按时间倒序排列

### ISSUE THREAD

**Issue by wq11123** [chatopera/cosin#11]
# 描述
历史会话点击任意访客，其访问/咨询时间，按时间倒序排列
## 现在行为

![](https://user-images.githubusercontent.com/40993206/44889827-4002be80-ad0a-11e8-8ef6-54c65670160c.png)
现在是时间无序排列
## 预期行为

# 解决方案

# 环境

* 代码版本:
The commit hash (`git rev-parse HEAD`)

**Comment by xianliwang** [comment]
@Samurais 企业版历史会话点击任意访客，其访问/咨询时间，按时间倒序排列

**Comment by xianliwang** [comment]
5.0版本，访客视图页面其访问/咨询时间，按时间倒序排列
