### ISSUE TITLE
部署完不能正常启动

### ISSUE THREAD

**Issue by qq31682216** [chatopera/cosin#128]
# 描述
按官网部署方式，要求都已经检查过没问题。
./scripts/start.sh 之后，打开http://YOUR_IP:8035/ 访问服务，返回404错误
查看日志

执行docker-compose ps，全部状态是up
               Name                              Command               State                           Ports                         
-------------------------------------------------------------------------------------------------------------------------------------
cosin_contact-center_1_a9b0373e6687   /opt/apache-tomcat/bin/cat ...   Up      8030/tcp, 8031/tcp, 8032/tcp, 8033/tcp, 8034/tcp,     
                                                                               8035/tcp, 0.0.0.0:8036->8036/tcp, 8037/tcp, 8038/tcp, 
                                                                               8039/tcp, 8040/tcp, 8041/tcp, 8042/tcp, 8043/tcp,     
                                                                               8044/tcp, 8045/tcp, 8046/tcp, 8047/tcp, 8048/tcp,     
                                                                               8049/tcp, 8050/tcp, 8051/tcp, 8052/tcp, 8053/tcp,     
                                                                               8054/tcp, 8055/tcp, 8056/tcp, 8057/tcp, 8058/tcp,     
                                                                               8059/tcp, 8060/tcp, 8061/tcp, 8062/tcp, 8063/tcp,     
                                                                               8064/tcp, 8065/tcp, 8066/tcp, 8067/tcp, 8068/tcp,     
                                                                               8069/tcp, 8070/tcp, 8071/tcp, 8072/tcp, 8073/tcp,     
                                                                               8074/tcp, 8075/tcp, 8076/tcp, 8077/tcp, 8078/tcp,     
                                                                               8079/tcp, 0.0.0.0:8035->8080/tcp, 8081/tcp, 8082/tcp, 
                                                                               8083/tcp, 8084/tcp, 8085/tcp, 8086/tcp, 8087/tcp,     
                                                                               8088/tcp, 8089/tcp, 8090/tcp, 9200/tcp, 9300/tcp      
cosin_elasticsearch_1_24d6d90a6154    /docker-entrypoint.sh elas ...   Up      0.0.0.0:8039->9200/tcp, 0.0.0.0:8040->9300/tcp        
cosin_mysql_1_cfdc3b6c0a16            docker-entrypoint.sh mysqld      Up      0.0.0.0:8037->3306/tcp                                
cosin_redis_1_4dcf0d770b50            docker-entrypoint.sh redis ...   Up      0.0.0.0:8041->6379/tcp          
看日志如下：
docker-compose logs -f contact-center 日志：
contact-center_1_a9b0373e6687 | Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
contact-center_1_a9b0373e6687 | 2018-11-03 20:53:07.818 [localhost-startStop-1] ERROR org.springframework.boot.SpringApplication - Application startup failed
contact-center_1_a9b0373e6687 | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationStartupListener': Unsatisfied dependency expressed through field 'elasticSearchTemplate'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'elasticsearchTemplate' defined in class path resource [org/springframework/boot/autoconfigure/data/elasticsearch/ElasticsearchDataAutoConfiguration.class]: Unsatisfied dependency expressed through method 'elasticsearchTemplate' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'elasticsearchClient' defined in class path resource [org/springframework/boot/autoconfigure/data/elasticsearch/ElasticsearchAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.elasticsearch.client.Client]: Factory method 'elasticsearchClient' threw exception; nested exception is java.lang.VerifyError: (class: org/jboss/netty/channel/socket/nio/NioWorkerPool, method: newWorker signature: (Ljava/util/concurrent/Executor;)Lorg/jboss/netty/channel/socket/nio/AbstractNioWorker;) Wrong return type in function
contact-center_1_a9b0373e6687 |         at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)
contact-center_1_a9b0373e6687 |         at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
contact-center_1_a9b0373e6687 |         at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
contact-center_1_a9b0373e6687 |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)

docker-compose logs -f elasticsearch 日志，有两段错误：
第一段错误：
Attaching to cosin_elasticsearch_1_24d6d90a6154
elasticsearch_1_24d6d90a6154 | [2018-11-03 12:33:30,511][DEBUG][bootstrap                ] unable to install syscall filter
elasticsearch_1_24d6d90a6154 | java.lang.UnsupportedOperationException: seccomp unavailable: your kernel is buggy and you should upgrade
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.bootstrap.Seccomp.linuxImpl(Seccomp.java:281)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.bootstrap.Seccomp.init(Seccomp.java:618)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.bootstrap.JNANatives.trySeccomp(JNANatives.java:183)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.bootstrap.Natives.trySeccomp(Natives.java:99)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:100)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:160)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:45)
elasticsearch_1_24d6d90a6154 | [2018-11-03 12:33:30,513][WARN ][bootstrap                ] unable to install syscall filter: seccomp unavailable: your kernel is buggy and you should upgrade
第二段错误：
elasticsearch_1_24d6d90a6154 | [2018-11-03 12:33:33,539][WARN ][watcher                  ] cannot notify file changes listener
elasticsearch_1_24d6d90a6154 | java.lang.IllegalArgumentException: script file extension not supported [gitignore]
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.script.ScriptService.getScriptEngineServiceForFileExt(ScriptService.java:220)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.script.ScriptService.access$1300(ScriptService.java:82)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.script.ScriptService$ScriptChangesListener.onFileInit(ScriptService.java:531)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.watcher.FileWatcher$FileObserver.onFileCreated(FileWatcher.java:256)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.watcher.FileWatcher$FileObserver.init(FileWatcher.java:166)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.watcher.FileWatcher$FileObserver.createChild(FileWatcher.java:173)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.watcher.FileWatcher$FileObserver.listChildren(FileWatcher.java:188)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.watcher.FileWatcher$FileObserver.onDirectoryCreated(FileWatcher.java:299)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.watcher.FileWatcher$FileObserver.init(FileWatcher.java:162)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.watcher.FileWatcher$FileObserver.access$000(FileWatcher.java:75)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.watcher.FileWatcher.doInit(FileWatcher.java:65)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.watcher.AbstractResourceWatcher.init(AbstractResourceWatcher.java:36)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.watcher.ResourceWatcherService.add(ResourceWatcherService.java:133)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.watcher.ResourceWatcherService.add(ResourceWatcherService.java:126)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.script.ScriptService.<init>(ScriptService.java:191)
elasticsearch_1_24d6d90a6154 |  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
elasticsearch_1_24d6d90a6154 |  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
elasticsearch_1_24d6d90a6154 |  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
elasticsearch_1_24d6d90a6154 |  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:50)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:886)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.SingleMethodInjector.inject(SingleMethodInjector.java:70)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:96)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:95)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:886)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:201)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:879)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:46)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.node.Node.<init>(Node.java:213)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.node.Node.<init>(Node.java:140)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
elasticsearch_1_24d6d90a6154 |  at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:45)

## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
请问操作系统是什么？
我们之前在 CentOS 7.2和Ubuntu 14.04 以上做过测试。
这个问题之前没有遇到过。

**Comment by qq31682216** [comment]
centOS 7.4，那我装个CentOS 7.2试试，多谢

**Comment by Samurais** [comment]
参考了 https://www.cnblogs.com/sloveling/p/elasticsearch.html 的介绍，应该是系统配置一下
打开的文件太多了，系统默认参数不支持。

**Comment by qq31682216** [comment]
CentOS 7.2 成功
