### ISSUE TITLE
客服端js报错

### ISSUE THREAD

**Issue by 654409314** [chatopera/cosin#133]
![image](https://user-images.githubusercontent.com/41300336/48115323-8261f200-e29d-11e8-8e51-d9b06c79dc3f.png)

# 描述
控制台js脚本报错：
 Cannot read property 'innerHTML' of undefined
 Layui hint: form is not a valid module
GET http://cc.chatopera.com/message/ping.html?_=1541570743921 502 (Bad Gateway)
## 现在行为
Uncaught TypeError: Cannot read property 'innerHTML' of undefined
CSKeFu_Rest_Request.v1.js:30 Rest api 返回的值：
layui.js:2 Layui hint: form is not a valid module
r @ layui.js:2
form.js:2 Uncaught TypeError: Cannot read property 'innerHTML' of undefined
CSKeFu_IM.v1.js:83 ping:1541571886111
form.js:2 Uncaught TypeError: Cannot read property 'innerHTML' of undefined
    at HTMLSelectElement.<anonymous> (form.js:2)
    at Function.each (jquery-1.10.2.min.js:4)
    at init.each (jquery-1.10.2.min.js:4)
    at select (form.js:2)
    at Function.<anonymous> (form.js:2)
    at t.fn.each (layui.js:2)
    at u.render (form.js:2)
    at form.js:2
    at t.r (layui.js:2)
    at c (layui.js:2)
layui.js:2 Layui hint: form is not a valid module
CSKeFu_IM.v1.js:83 ping:1541571946111
CSKeFu_IM.v1.js:83 ping:1541572006109
CSKeFu_IM.v1.js:83 ping:1541572067021
CSKeFu_IM.v1.js:82 GET http://cc.chatopera.com/message/ping.html?_=1541570743921 502 (Bad Gateway)
## 预期行为
 影响到消息接收发送和前端页面展示问题
# 解决方案
   目前还没有解决
# 环境
  windows
* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
使用最新的code，经测试没有问题。

![image](https://user-images.githubusercontent.com/3538629/48116203-509e5a80-e2a0-11e8-9454-4cf73c943210.png)

**Comment by 654409314** [comment]
但是这个500网关错误仍存在，CSKeFu_IM.v1.js:82 GET http://cc.chatopera.com/message/ping.html?_=1541570743921 502 (Bad Gateway)
