### ISSUE TITLE
偶尔会发不出去消息

### ISSUE THREAD

**Issue by 654409314** [chatopera/cosin#134]
# 描述
发不出去消息，顾客端和客服端都有重现，是间隔一阵子后浏览器没有动客服和顾客端也都没有主动结束会话但是发消息就发不出去
## 预期行为

# 解决方案
暂时未解决
# 环境
windows pc和mobile
* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by xianliwang** [comment]
@Samurais 企业版没有这个问题

**Comment by Samurais** [comment]
5.0.0版本已经解决此问题。
