### ISSUE TITLE
状态不正确

### ISSUE THREAD

**Issue by 654409314** [chatopera/cosin#136]
# 描述
有时顾客端访问了退到后台客服端一直显示在线，但有时候会显示离线，客服端显示顾客已离开，但是顾客仍然可以发送消息，状态不正确,及时顾客端刷新了客服端状态也不变
## 预期行为
![image](https://user-images.githubusercontent.com/41300336/48127064-cfee5700-e2bd-11e8-8225-2a9874ed8203.png)

# 解决方案
未解决
# 环境
windows pc 和mobile
* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by xianliwang** [comment]
@Samurais 企业版没有这个问题

**Comment by Samurais** [comment]
v5.0.0版本已经解决此问题。
