### ISSUE TITLE
配置文件的示例见 settings.xml。打开404

### ISSUE THREAD

**Issue by 654409314** [chatopera/cosin#137]
# 描述
https://github.com/chatopera/cosin/wiki/春松客服：开发环境#依赖
下面的“修改maven2配置”，点击配置文件的示例见 settings.xml，跳转404
## 现在行为
配置文件的示例见 settings.xml，跳转404
![image](https://user-images.githubusercontent.com/41300336/48171099-56924b00-e335-11e8-9d77-c232fd5326a5.png)
![image](https://user-images.githubusercontent.com/41300336/48171113-690c8480-e335-11e8-9821-ff8af3558074.png)

## 预期行为

# 解决方案
文件地址丢失，未解决
# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
现在不需要使用这个setttings.xml文件配置了，只要在pom.xml中加入

```
    <repositories>
        <repository>
            <id>chatopera</id>
            <name>Chatopera Inc.</name>
            <url>https://nexus.chatopera.com/repository/maven-public</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
```

另外，请使用最新的Java SDK，以避免遇到``` unable to find valid certification path to requested target```，详细介绍见[无法下载jar包](https://github.com/chatopera/chatopera-sample-java/issues/1)。
