### ISSUE TITLE
[cc]两个不同页面的在线客服业务概况，icon一致，功能不同

### ISSUE THREAD

**Issue by wq11123** [chatopera/cosin#14]
# 描述
首页和系统管理默认都有在线客服业务概况，icon一致，命名不同
## 现在行为

![](https://user-images.githubusercontent.com/40993206/44844848-84e11380-ac7e-11e8-9488-d6fb72ed59d3.png)

![](https://user-images.githubusercontent.com/40993206/44844857-87dc0400-ac7e-11e8-9bc3-16c23cf82ffa.png)

## 预期行为

# 解决方案

# 环境

* 代码版本:
The commit hash (`git rev-parse HEAD`)

**Comment by xianliwang** [comment]
功能不一样，设计如此
