### ISSUE TITLE
执行sql文件没有执行成功

### ISSUE THREAD

**Issue by 654409314** [chatopera/cosin#140]
# 描述
缺少表：contactcenter.cs_callout_dialplan
原因：执行sql文件没有执行成功
![image](https://user-images.githubusercontent.com/41300336/48182068-dd125100-e364-11e8-8687-79083c054214.png)

## 现在行为
运行报错
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'contactcenter.cs_callout_dialplan' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

## 预期行为

# 解决方案
 
# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by 654409314** [comment]
从高版本的mysql导数据到低版本，去掉
 `createtime` DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '创建日期',
  `updatetime` DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
中的ON UPDATE CURRENT_TIMESTAMP后执行成功；

在MySQL 5.6.5版本之前，DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP只适用于TIMESTAMP，而且一张表中，最多允许一个TIMESTAMP字段采用该特性。 从MySQL 5.6.5开始， DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP同时适用于TIMESTAMP和DATETIME，且不限制数量。

**Comment by Samurais** [comment]
目前默认支持mysql 5.6，对于5.7，需要关闭SQL语法的strict关键字，就是对日期校验的，默认是strict。
