### ISSUE TITLE
客服在线顾客上来提示让留言

### ISSUE THREAD

**Issue by 654409314** [chatopera/cosin#141]
# 描述
客服在线，顾客上来提示让留言
![image](https://user-images.githubusercontent.com/41300336/48187669-c37a0500-e376-11e8-85a6-100472ddeb62.png)

## 预期行为

# 解决方案
未解决
# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
有没有开启坐席工作时间？默认好像是开启的。这个你可以查看一下代码。
