### ISSUE TITLE
客服正常在线维和顾客端不能发送了点击提示客服端已断开

### ISSUE THREAD

**Issue by 654409314** [chatopera/cosin#142]
# 描述
![image](https://user-images.githubusercontent.com/41300336/48189280-c8d94e80-e37a-11e8-9de9-95649172de5b.png)

![image](https://user-images.githubusercontent.com/41300336/48189428-22417d80-e37b-11e8-924b-3f6b0d8ec256.png)
客服端仍可以发送，但是顾客端发不了文本框变成了display

客服端经常突然发不了消息了查看浏览器控制台是链接断开了但是不知道js重连机制在写在哪
![image](https://user-images.githubusercontent.com/41300336/48190288-4bfba400-e37d-11e8-9b6f-9c1b6794a954.png)

## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
感谢提交，我暂时没有遇到过，如果是bug，会优先处理。

**Comment by Samurais** [comment]
另外，尝试一下最新的代码，上周曾做过一个坐席端连接的优化。

**Comment by xianliwang** [comment]
@Samurais 企业版没有这个问题，坐席主动断开会话后，访客不能编辑发送消息。
