### ISSUE TITLE
在阿里云Ubuntu18.04上面，docker运行后不能正常使用

### ISSUE THREAD

**Issue by zsinba** [chatopera/cosin#144]
# 描述
系统： Ubuntu18.04
Docker版本：Docker version 18.09.0, build 4d60db4
Docker-compose版本：docker-compose version 1.17.1, build unknown
部署方式：
git clone最新代码，（20181111）
./script/start.sh
运行截图：
![image](https://user-images.githubusercontent.com/890157/48322260-a50b5680-e661-11e8-932b-9d0cea8e7682.png)

## 现在行为
未做操作
## 预期行为
正常打开http://domain:8035,但并没打开。
尝试连接数据库，通过domain:8037,可以正常连接数据库的
# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by zsinba** [comment]
服务器配置：
8核32G
网络100M
阿里云ECS，官方Ubuntu 18.04系统

**Comment by kylezhang** [comment]
防火墙8035,8036开下。

**Comment by zsinba** [comment]
防火墙都开了这两个端口的。
请求时，我发现系统已经接受这两个请求，但是Tomcat端没有收到请求。
怀疑跟IPV6映射有关，但是默认就是IPV6，我尝试使用127或者0.0.0.0绑定，也是不可以。

**Comment by ip-productions** [comment]
完全同样的问题。

只有一点不同
》尝试连接数据库，通过domain:8037,可以正常连接数据库的
我这边始终说密码错误
无论是用root和123456，还是admin和admin123456

**Comment by zsinba** [comment]
我放弃docker了

**Comment by shangkaisk** [comment]
centos 部署，部署方式与楼主一样 git+docker，chrome访问http://domain:8035 报错，提示 ERR_CONNECTION_RESET。
检查了telnet端口是通的。http访问就不可以了
有解决此问题的吗？求帮助

**Comment by wangpengli** [comment]
我在云端aliyun ubuntu 18.04正常。
在本地centos 7.5 ，正常。

**Comment by Samurais** [comment]
@wangpengli  感谢反馈！

初步断定是网络问题，可以尝试使用iptables关闭防火墙。

```
apt-get install ufw -y
ufw disable
```
