### ISSUE TITLE
手机端显示附件问题

### ISSUE THREAD

**Issue by 654409314** [chatopera/cosin#151]
# 描述
![image](https://user-images.githubusercontent.com/41300336/48458839-ebe48200-e802-11e8-946e-3d0c46c8d525.png)

## 预期行为

# 解决方案
在文件：contact-center\app\src\main\resources\templates\apps\im\mobile.html
增加手机端接收附件的判断代码：
![image](https://user-images.githubusercontent.com/41300336/48458912-3108b400-e803-11e8-978d-fd45ffdec25f.png)

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by xianliwang** [comment]
已解决
