### ISSUE TITLE
首页被重复嵌套了

### ISSUE THREAD

**Issue by 654409314** [chatopera/cosin#152]
# 描述
![image](https://user-images.githubusercontent.com/41300336/48473579-b7d58500-e833-11e8-8b95-773ded1853c8.png)

![image](https://user-images.githubusercontent.com/41300336/48473722-05ea8880-e834-11e8-8469-b71a02b818c7.png)

## 预期行为

# 解决方案
cosin-develop\contact-center\app\src\main\resources\templates\apps\index.html
加入
// 在被嵌套时就刷新上级窗口
if(window.parent != window){
    window.parent.location.reload(true);
}
无用代码建议下次更新去掉：
cosin-develop\contact-center\app\src\main\resources\templates\apps\index2.html没啥用
# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by xianliwang** [comment]
@Samurais 企业版没有首页嵌套问题

**Comment by Samurais** [comment]
升级到5.0.0版本解决此问题。
