### ISSUE TITLE
部署后怎么访问

### ISSUE THREAD

**Issue by ykasbdg** [chatopera/cosin#158]
# 描述

## 预期行为

# 解决方案
单服务器部署后访问地址：http://YOUR_IP:8035/访问服务。这个"访问服务"应该是项目名称吧， 这个项目名称叫什么呢？
# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
```http://YOUR_IP:8035/```就是能打开登录页面，不需要加其他路径。

确认防火墙允许 8035和8036端口访问。

**Comment by ykasbdg** [comment]
嗯 部署后怎么访问？

**Comment by ykasbdg** [comment]
防火墙关闭了

**Comment by Samurais** [comment]
查看服务状态：

```
cd cosin
docker-compose ps # 确认各个服务正常
docker-compose logs -f contact-center # 确认cc日志正常
```

使用浏览器打开```http://YOUR_IP:8035/```

**Comment by ykasbdg** [comment]
[root@localhost cosin]# docker-compose ps
          Name                      Command              State               Ports          
--------------------------------------------------------------------------------------------
cosin_contact-              /opt/apache-               Restarting                           
center_1_9181160834c0       tomcat/bin/cat ...                                              
cosin_elasticsearch_1_e12   /docker-entrypoint.sh      Up           0.0.0.0:8039->9200/tcp, 
604f1411a                   elas ...                                0.0.0.0:8040->9300/tcp  
cosin_mysql_1_e3581f30830   docker-entrypoint.sh       Up           0.0.0.0:8037->3306/tcp  
8                           --max ...                                                       
cosin_redis_1_19d1f17cb21   docker-entrypoint.sh       Up           0.0.0.0:8041->6379/tcp  
3                           redis ...                                                       
[root@localhost cosin]#

**Comment by ykasbdg** [comment]
contact-center_1_9181160834c0 | WritebackTmp:          0 kB
contact-center_1_9181160834c0 | CommitLimit:     1347412 kB
contact-center_1_9181160834c0 | Committed_AS:    2860668 kB
contact-center_1_9181160834c0 | VmallocTotal:   34359738367 kB
contact-center_1_9181160834c0 | VmallocUsed:        5496 kB
contact-center_1_9181160834c0 | VmallocChunk:   34359729396 kB
contact-center_1_9181160834c0 | HardwareCorrupted:     0 kB
contact-center_1_9181160834c0 | AnonHugePages:         0 kB
contact-center_1_9181160834c0 | CmaTotal:              0 kB
contact-center_1_9181160834c0 | CmaFree:               0 kB
contact-center_1_9181160834c0 | HugePages_Total:       0
contact-center_1_9181160834c0 | HugePages_Free:        0
contact-center_1_9181160834c0 | HugePages_Rsvd:        0
contact-center_1_9181160834c0 | HugePages_Surp:        0
contact-center_1_9181160834c0 | Hugepagesize:       2048 kB
contact-center_1_9181160834c0 | DirectMap4k:       65472 kB
contact-center_1_9181160834c0 | DirectMap2M:      983040 kB
contact-center_1_9181160834c0 | CPU:total 1 (initial active 1) (1 cores per cpu, 1 threads per core) family 6 model 158 stepping 11, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, po
pcnt, avx, aes, clmul, 3dnowpref, lzcnt, tsc, tscinvbit
contact-center_1_9181160834c0 | /proc/cpuinfo:
contact-center_1_9181160834c0 | processor       : 0
contact-center_1_9181160834c0 | vendor_id       : GenuineIntel
contact-center_1_9181160834c0 | cpu family      : 6
contact-center_1_9181160834c0 | model           : 158
contact-center_1_9181160834c0 | model name      : Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
contact-center_1_9181160834c0 | stepping        : 11
contact-center_1_9181160834c0 | cpu MHz         : 3600.008
contact-center_1_9181160834c0 | cache size      : 6144 KB
contact-center_1_9181160834c0 | physical id     : 0
contact-center_1_9181160834c0 | siblings        : 1
contact-center_1_9181160834c0 | core id         : 0
contact-center_1_9181160834c0 | cpu cores       : 1
contact-center_1_9181160834c0 | apicid          : 0
contact-center_1_9181160834c0 | initial apicid  : 0
contact-center_1_9181160834c0 | fpu             : yes
contact-center_1_9181160834c0 | fpu_exception   : yes
contact-center_1_9181160834c0 | cpuid level     : 22
contact-center_1_9181160834c0 | wp              : yes
contact-center_1_9181160834c0 | flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl x
topology nonstop_tsc eagerfpu pni pclmulqdq monitor ssse3 cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch rdseed clflushopt
contact-center_1_9181160834c0 | bogomips        : 7200.01
contact-center_1_9181160834c0 | clflush size    : 64
contact-center_1_9181160834c0 | cache_alignment : 64
contact-center_1_9181160834c0 | address sizes   : 39 bits physical, 48 bits virtual
contact-center_1_9181160834c0 | power management:
contact-center_1_9181160834c0 | Memory: 4k page, physical 1015476k(633088k free), swap 839676k(166012k free)
contact-center_1_9181160834c0 | vm_info: Java HotSpot(TM) 64-Bit Server VM (25.144-b01) for linux-amd64 JRE (1.8.0_144-b01), built on Jul 21 2017 21:57:33 by "java_re" with gcc 4.3.0 20080428 (Red 
Hat 4.3.0-8)
contact-center_1_9181160834c0 | time: Sat Nov 17 14:39:42 2018
contact-center_1_9181160834c0 | elapsed time: 0 seconds (0d 0h 0m 0s)

**Comment by ykasbdg** [comment]
[root@localhost cosin]# firewall-cmd --zone=public --add-port=8035/tcp --permanent
success
[root@localhost cosin]# firewall-cmd --zone=public --add-port=8036/tcp --permanent
success

**Comment by ykasbdg** [comment]
请问 各个服务正常么？

**Comment by cklx0719** [comment]
我和你的情况一下，重新弄了N次都是cosin_contact这个东东一直在restarting。

**Comment by cklx0719** [comment]
找到原因了，，，内存太小，至少得准备8G内存，我跑这个项目，就白多了5G多的内存占用。。。
