### ISSUE TITLE
当前在线用户列表显示信息不完整不正确

### ISSUE THREAD

**Issue by 654409314** [chatopera/cosin#159]
# 描述
访问轨迹 没有来源页、当前页、搜索引擎、关键词、 现有的浏览器类型判断也不正确

## 预期行为

# 解决方案
待解决
# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by xianliwang** [comment]
@Samurais 企业版没有这个问题

**Comment by xianliwang** [comment]
![image](https://user-images.githubusercontent.com/52594347/72599495-c8f4b700-394c-11ea-861d-b1eaf9a44e72.png)
