### ISSUE TITLE
数据不同

### ISSUE THREAD

**Issue by 654409314** [chatopera/cosin#162]
# 描述

![image](https://user-images.githubusercontent.com/41300336/48699605-ce5d5100-ec24-11e8-963c-213fd8269fb6.png)
![image](https://user-images.githubusercontent.com/41300336/48700788-d8cd1a00-ec27-11e8-919a-6a8d95bf5f34.png)

多刷新页面后就没有了
## 预期行为
同步更新数据和状态
# 解决方案
 
# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
在新版本v5.0.0中解决。
