### ISSUE TITLE
使用docker-compose时遇到错误

### ISSUE THREAD

**Issue by goryghost** [chatopera/cosin#166]
# 描述
运行docker-compose up -d mysql 命令后显示有路径方面的问题，请问这种情况应该如何处理呢？
（运行docker-compose up -d redis 时也会遇到同样的问题）

G:\prog\GitHub\cosin>docker-compose up -d mysql
WARNING: The PWD variable is not set. Defaulting to a blank string.
Creating cosin_mysql_1 ... error

ERROR: for cosin_mysql_1  Cannot create container for service mysql: b'Mount denied:\nThe source path "\\\\mysql\\\\config:/etc/mysql"\nis not a valid Windows path'

ERROR: for mysql  Cannot create container for service mysql: b'Mount denied:\nThe source path "\\\\mysql\\\\config:/etc/mysql"\nis not a valid Windows path'
ERROR: Encountered errors while bringing up the project.

## 现在行为
![image](https://user-images.githubusercontent.com/8553830/48964467-f3661100-efe2-11e8-8c9c-b7cd4dea19de.png)

## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
我们默认的安装环境为Mac或Linux，如果是Windows，请自行修改docker-compose.yml文件。在Volume里使用Windows路径格式。
 




------------------
Cheers.
Hai Liang Wang, CEO, Chatopera




 
 
 
------------------ Original ------------------
From: "goryghost"; 
Date: 2018年11月24日(星期六) 中午12:23
To: "chatopera/cosin"; 
Cc: "Subscribed"; 
Subject: [chatopera/cosin] 使用docker-compose时遇到错误 (#166)

 

描述
 
运行docker-compose up -d mysql 命令后显示有路径方面的问题，请问这种情况应该如何处理呢？
 （运行docker-compose up -d redis 时也会遇到同样的问题）
 
G:\prog\GitHub\cosin>docker-compose up -d mysql
 WARNING: The PWD variable is not set. Defaulting to a blank string.
 Creating cosin_mysql_1 ... error
 
ERROR: for cosin_mysql_1  Cannot create container for service mysql: b'Mount denied:\nThe source path "\\mysql\\config:/etc/mysql"\nis not a valid Windows path'
 
ERROR: for mysql  Cannot create container for service mysql: b'Mount denied:\nThe source path "\\mysql\\config:/etc/mysql"\nis not a valid Windows path'
 ERROR: Encountered errors while bringing up the project.
 
现在行为
 

 
预期行为
 
解决方案
 
环境
  
代码版本:
 Git commit hash (git rev-parse HEAD)

**Comment by Samurais** [comment]
![image](https://user-images.githubusercontent.com/3538629/48965170-3def8980-eff3-11e8-919d-3fe81274f9bf.png)
