### ISSUE TITLE
[cc]客服与webim在线访客对话时，客服离线，还能成功发送信息

### ISSUE THREAD

**Issue by wq11123** [chatopera/cosin#17]
# 描述
客服与webim在线访客对话时，客服掉线，还能成功发送信息，并且客服名称由自定义姓名变为登录时用户名
## 现在行为

![](https://user-images.githubusercontent.com/40993206/44838730-7f300180-ac6f-11e8-8873-50272a4bad64.png)

## 预期行为

# 解决方案

# 环境

* 代码版本:
The commit hash (`git rev-parse HEAD`)

**Comment by xianliwang** [comment]
设计如此
