### ISSUE TITLE
Ip定位错误,希望修改到ipip.net

### ISSUE THREAD

**Issue by myqmdx** [chatopera/cosin#174]
# 描述
IP所属地显示错误，希望修正
## 现在行为
IP所属地显示错误
## 预期行为
ip所属地正确显示
# 解决方案
希望修改到ipip.net或者其他正确率比较高的接口.目前ip112.42.81.*被定位到上海，实际应为辽宁大连移动
# 环境
无
* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
收到，感谢反馈！ 




------------------
Cheers.
Hai Liang Wang, CEO, Chatopera




 
 
 
------------------ Original ------------------
From: "myqmdx"; 
Date: 2018年12月18日(星期二) 晚上8:42
To: "chatopera/cosin"; 
Cc: "Subscribed"; 
Subject: [chatopera/cosin] Ip定位错误,希望修改到ipip.net (#174)

 

描述
 
IP所属地显示错误，希望修正
 
现在行为
 
IP所属地显示错误
 
预期行为
 
ip所属地正确显示
 
解决方案
 
希望修改到ipip.net或者其他正确率比较高的接口.目前ip112.42.81.*被定位到上海，实际应为辽宁大连移动
 
环境
 
无
  
代码版本:
 Git commit hash (git rev-parse HEAD)

**Comment by Samurais** [comment]
duplicated with #163
