### ISSUE TITLE
关于部署上云上服务器,域名绑定后的问题

### ISSUE THREAD

**Issue by qiangqiang666** [chatopera/cosin#179]
# 描述
本地调试好后,我丢在阿里云ecs服务器上,如果我使用ip+端口的形式访问,那什么问题都没有,如果我配置了nginx,把IP+8035和IP+8036绑定在两个域名上,那么就出现问题了,在后台管理中,客服不能发消息给用户,用户可以给客服发消息
## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by qiangqiang666** [comment]
好的,谢谢,既然使用两个域名不行,那我就直接去将两个端口配置在一个域名上!

**Comment by Samurais** [comment]
设置如下环境变量

```
export CS_IM_SERVER_SSL_PORT=80
```
