### ISSUE TITLE
无法以非ROOT部署

### ISSUE THREAD

**Issue by xinwo** [chatopera/cosin#180]
# 描述
server.context-path不是“/”时，页面无法正常加载，均报404
有什么方法可以不以ROOT部署吗？

## 预期行为

# 解决方案

# 环境
mac
eclipse

* 代码版本:
724ad60153bf60abdedaa376132b32401b5ca1b5

**Comment by Samurais** [comment]
这个我们没有试过，context path = "/"是春松客服推荐用法。
