### ISSUE TITLE
./scripts/start.sh执行完后，直接在运行机器上执行没反应http://127.0.0.1:8035，http://localhost:8035,都没反应

### ISSUE THREAD

**Issue by zhangyanbo2007** [chatopera/cosin#181]
# 描述

## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by zhangyanbo2007** [comment]
![image](https://user-images.githubusercontent.com/9403745/53466220-15f94180-3a8c-11e9-9bb8-f2b6ddaba1c6.png)

**Comment by zhangyanbo2007** [comment]
![image](https://user-images.githubusercontent.com/9403745/53466236-27dae480-3a8c-11e9-97e6-ae9c80364fa4.png)

**Comment by zhangyanbo2007** [comment]
![image](https://user-images.githubusercontent.com/9403745/53466350-899b4e80-3a8c-11e9-8cd3-09db4df88aaf.png)

**Comment by Samurais** [comment]
这个问题是contact center的image有问题，已经修复，请使用最新的代码或docker image.

**Comment by zhangyanbo2007** [comment]
ok，希望每次都做好测试再发布
