### ISSUE TITLE
[contact-center]访客端 单一窗口样式问题

### ISSUE THREAD

**Issue by zsh1314159** [chatopera/cosin#182]
# 描述   
在客服系统后台设置访客端单一窗口的风格时，单一窗口的发送按钮颜色无变化（未受到后台风格设置影响）。
![O@ `EB)H2K~)UA4TO8DX6GU](https://user-images.githubusercontent.com/38684889/54664597-aa9d0f80-4b1f-11e9-980c-fa1c6a983ad4.png)

## 现在行为
![8C(55MTA}PPG 1G)1H72@7L](https://user-images.githubusercontent.com/38684889/54664641-cdc7bf00-4b1f-11e9-9ecc-b90bd12b03a6.png)

## 预期行为
 发送按钮变为蓝色

# 解决方案 
未找到好的解决方案，目前是手动在单一窗口的html页面设置的style样式：
单一窗口html位置：contact-center\app\src\main\resources\templates\apps\im\index.html
![QQ截图20190320145635](https://user-images.githubusercontent.com/38684889/54665028-d2d93e00-4b20-11e9-9d2e-680808d3a831.png)

# 环境
windows
* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
这个按钮和title的背景应不应该一致是一个需要考虑的问题，我个人认为是不一致的，从设计上，这个按钮需要突出，配置强调色。
