### ISSUE TITLE
这套系统是全部开源的还是授权收费的？

### ISSUE THREAD

**Issue by lovemelovemydog** [chatopera/cosin#183]
# 描述

## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
开源：
https://github.com/chatopera/cosin

授权证书：
Apache 2.0

 付费：
机器人客服，呼叫中心技术支持，其他定制化服务

春松客服[公有云版本](https://github.com/chatopera/cosin/wiki/%E6%98%A5%E6%9D%BE%E5%AE%A2%E6%9C%8D%E4%B8%8A%E6%9E%B6%E9%9D%92%E4%BA%91AppCenter)

更多文档：

https://github.com/chatopera/cosin/wiki
