### ISSUE TITLE
是否可以不使用docker安装

### ISSUE THREAD

**Issue by wxb729** [chatopera/cosin#184]
# 描述
能否不使用docker进行安装
## 现在行为
已安装elasticsearch、redis、mysql等所需组件
## 预期行为
希望编译程序为war包在tomcat下执行
# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
可以不用docker安装，其实只要弄明白contact-center的配置文件application.properties就能选择自己的安装方式，主要配置为: mysql, elasticsearch, redis. 各软件版本参考：
[docker-compose.yml](https://github.com/chatopera/cosin/blob/develop/docker-compose.yml)

除我们配置的软件版本外，其他版本不一定支持，尤其是mysql和elasticsearch请保持一致。

## 如何 build war包
参考 contact-center的 [Dockerfile](https://github.com/chatopera/cosin/blob/develop/contact-center/Dockerfile).
