### ISSUE TITLE
平台如何打通微信小程序（小程序是原生的webscoket，春松是netty-socketio

### ISSUE THREAD

**Issue by Allienliyitai** [chatopera/cosin#188]
# 描述

## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
websocket以及socketio都是维护的双工通信的连接，借此实现异步通信机制。
在春松客服及你的websocket中间，可以用ActiveMQ实现消息的订阅和发布，不管消息怎么路由，都是已坐席人员的ID和访客的ID进行分发。

另外，如果使用小程序，建议集成腾讯的云通信服务：
https://cloud.tencent.com/login?s_url=https%3A%2F%2Fconsole.cloud.tencent.com%2Favc

如果用云通信，不但各种SDK都做好了，而且非常稳定，可以更快的和春松客服集成。

**Comment by Samurais** [comment]
目前春松客服的消息路由是怎么支持网页端的？
可以参考一下这里：https://github.com/chatopera/cosin/issues/111

这对实现集成小程序有启发，同时也可以参考春松客服如何集成Chatopera 机器人平台的代码。
