### ISSUE TITLE
部署https失败，客户端和客服端不能正常通信

### ISSUE THREAD

**Issue by caiaoxiao** [chatopera/cosin#189]
# 描述
在本地想配置成https，用https://<localhost>:8035的方式访问页面，但是用网页客户端访问的时候发现客户和客服不能聊天，应该如何部署。我的方式是先使用
`keytool -genkey -alias tomcat  -storetype PKCS12 -keyalg RSA -keysize 2048  -keystore keystore.p12 -validity 3650`生成一个p12文件，然后把这个文件放到/cosin/contact-center/app/src/main/resources目录下，修改application.properties，加入代码
```
server.ssl.key-store: classpath:keystore.p12
server.ssl.key-store-password: 123456
server.ssl.keyStoreType: PKCS12
server.ssl.keyAlias: tomcat
```
## 现在行为
使用ip:8035能工作，但是配置了网页客户端以后，客户端和客服能进入聊天界面，但是不能进行聊天
![image](https://user-images.githubusercontent.com/19814711/57980710-4637f700-7a61-11e9-8483-f0646b57d483.png)
![image](https://user-images.githubusercontent.com/19814711/57980721-62d42f00-7a61-11e9-91f3-e9f0c025623c.png)

## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
看浏览器的 console.log, 通信端口默认是8036
