### ISSUE TITLE
是否可以将客服对话功能嵌入到手机App中

### ISSUE THREAD

**Issue by bobokingbao** [chatopera/cosin#190]
# 描述
是否可以将客服对话功能嵌入到手机App中
## 预期行为

# 解决方案

# 环境
Ios，安卓
* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
目前客服端能适应手机浏览器，如果有体验不好的地方，欢迎反馈。
访客端可以在App中使用WebView打开聊天页面。
