### ISSUE TITLE
服务器部署报错

### ISSUE THREAD

**Issue by runzi** [chatopera/cosin#193]
# 描述
部署服务器报错

Pulling mysql          ... done
Pulling redis          ... done
Pulling elasticsearch  ... done
Pulling contact-center ... done
Creating cosin_mysql_1 ... 
Creating cosin_redis_1 ... 
Creating cosin_mysql_1         ... error

ERROR: for cosin_elasticsearch_1  Cannot start service elasticsearch: b'failed to update store for object type *libnetwork.endpointCnt: Key not found in store'
Creating cosin_redis_1         ... error
ERROR: for cosin_mysql_1  Cannot start service mysql: b'failed to update store for object type *libnetwork.endpointCnt: Key not found in store'

ERROR: for cosin_redis_1  Cannot start service redis: b'failed to update store for object type *libnetwork.endpointCnt: Key not found in store'

ERROR: for elasticsearch  Cannot start service elasticsearch: b'failed to update store for object type *libnetwork.endpointCnt: Key not found in store'

ERROR: for mysql  Cannot start service mysql: b'failed to update store for object type *libnetwork.endpointCnt: Key not found in store'

ERROR: for redis  Cannot start service redis: b'failed to update store for object type *libnetwork.endpointCnt: Key not found in store'
ERROR: Encountered errors while bringing up the project.

**Comment by Samurais** [comment]
操作系统类型，部署位置，部署使用账号，内存大小请提供一下。

**Comment by runzi** [comment]
CentOS 7.2 64bit
CPU：4 CPUs内存：8192 M硬盘：80 G带宽：3 M流量：不限
root登录

**Comment by runzi** [comment]
部署在/www/cosin下

**Comment by Samurais** [comment]
是这个操作系统内部运行docker的问题，这个问题我们之前没有遇到过，因为我们服务器统一用Ubuntu，
相关的解答请参考网络，比如 https://geekori.com/details.php?que_id=9404
