### ISSUE TITLE
外呼系统/通话记录中，无法播放录制的通话录音

### ISSUE THREAD

**Issue by wangpengli** [chatopera/cosin#194]
# 描述
外呼系统/通话记录中，无法播放录制的通话录音，点击在线听，提示“执行中，请稍候”，界面显示一段时间后退出，无任何提示。
原先log提示minio服务查询失败，修改相关地址和端口，key，等信息后，没有了错误提示，只有：

## 现在行为
提示minio相关服务地址为192.168.2.217
## 预期行为

# 解决方案
修改相应的配置文件为实际minio地址和key，解决。
# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)
3.9.0

**Comment by Samurais** [comment]
分布式存储服务配置文件

```
contact-center/app/src/main/resources/application.properties
```

默认配置值：
```
storage.minio.url=http://192.168.2.217:9000
storage.minio.access_key=M19Q8YJ8FzLyQtST7r0
storage.minio.secret_key=KHv6qjddHD4HfR1m7fjY7Hgl
```

这几个值也可以通过环境变量来配置，在[docker-compose.yml](https://github.com/chatopera/cosin/blob/develop/docker-compose.yml)中如下：


```
STORAGE_MINIO_URL=
STORAGE_MINIO_ACCESS_KEY=
STORAGE_MINIO_SECRET_KEY=
```

**Comment by wangpengli** [comment]
环境变量说法准确吗？所有代码中并未grep到任何一个引用。

Samurais <notifications@github.com> 于2019年7月2日周二 下午12:34写道：

**Comment by Samurais** [comment]
这个是Spring Boot的特性：

```
If you use environment variables rather than system properties, most operating systems disallow period-separated key names, but you can use underscores instead (for example, SPRING_CONFIG_NAME instead of spring.config.name).
```

文档：
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

**Comment by wangpengli** [comment]
手动，多谢。

Samurais <notifications@github.com> 于2019年7月3日周三 下午7:39写道：
