### ISSUE TITLE
项目编译失败

### ISSUE THREAD

**Issue by 1haikuotiankong** [chatopera/cosin#199]
github项目导进来以后，会导入两个项目，一个sdk,一个contact-cengter
pom.xml 里面有com.chatopera.bot  找不到，根据artifactId 发现这个可能是groupid拼错，应该是sdk项目自定义的com.chatopera.chatbot
重新编译后，pom.xml没报错，但发现/contact-center/src/main/java/mondrian/olap/Util.java这个文件中import org.eigenbase.xom.XOMUtil失败

**Comment by Samurais** [comment]
在wiki中根据“春松客服开发文档”搭建环境，
https://github.com/chatopera/cosin/wiki

——————
https://bot.chatopera.com
企业聊天机器人平台

------------------ 原始邮件 ------------------
发件人: 1haikuotiankong <notifications@github.com>
发送时间: 2019年7月12日 15:05
收件人: chatopera/cosin <cosin@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[chatopera/cosin] 项目编译失败 (#199)




github项目导进来以后，会导入两个项目，一个sdk,一个contact-cengter
 pom.xml 里面有com.chatopera.bot  找不到，根据artifactId 发现这个可能是groupid拼错，应该是sdk项目自定义的com.chatopera.chatbot
 重新编译后，pom.xml没报错，但发现/contact-center/src/main/java/mondrian/olap/Util.java这个文件中import org.eigenbase.xom.XOMUtil失败

**Comment by 1haikuotiankong** [comment]
> 在wiki中根据“春松客服开发文档”搭建环境， https://github.com/chatopera/cosin/wiki —————— https://bot.chatopera.com 企业聊天机器人平台
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 1haikuotiankong <notifications@github.com> 发送时间: 2019年7月12日 15:05 收件人: chatopera/cosin <cosin@noreply.github.com> 抄送: Subscribed <subscribed@noreply.github.com> 主题: 回复：[chatopera/cosin] 项目编译失败 (#199) github项目导进来以后，会导入两个项目，一个sdk,一个contact-cengter pom.xml 里面有com.chatopera.bot 找不到，根据artifactId 发现这个可能是groupid拼错，应该是sdk项目自定义的com.chatopera.chatbot 重新编译后，pom.xml没报错，但发现/contact-center/src/main/java/mondrian/olap/Util.java这个文件中import org.eigenbase.xom.XOMUtil失败 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

这啥

**Comment by Samurais** [comment]
![image](https://user-images.githubusercontent.com/3538629/61171095-4c4fdd00-a5a5-11e9-96d3-3026174da413.png)

相关jar包在chatopera nexus中。

**Comment by ws364744954** [comment]
哥 你解决了没有哈。 我也碰到这个问题，pom.xml  jar包 下载不了

**Comment by JoeCoding-cn** [comment]
> 哥你解决了没有哈。我也碰到这个问题，pom.xml jar包下载不了

 请问你解决了么  jar包下载不了

**Comment by Samurais** [comment]
参考最新的部署文档：
https://docs.chatopera.com/products/cskefu/deploy.html
