### ISSUE TITLE
新建坐席无法会话

### ISSUE THREAD

**Issue by 1haikuotiankong** [chatopera/cosin#201]
新建了一个坐席用户并开启了在线开关，但是无法会话以及无法回复

**Comment by Samurais** [comment]
坐席一定要指定到一个组织机构中才能接起访客请求。

**Comment by xianliwang** [comment]
@Samurais 企业版没有这个问题

**Comment by Zct-123** [comment]
我的是管理员创建的账号接收不到用户的对话

![4 76 1DMMG5R}657 _E(CMY](https://user-images.githubusercontent.com/57829156/68991435-dda7c680-0899-11ea-8d62-e541af738b49.png)

**Comment by Samurais** [comment]
@Zct-123 在线坐席人数为3，有分配策略，该会话未必会发送给管理员。

请另外建立issue描述设置。
