### ISSUE TITLE
春松客服占满CPU资源

### ISSUE THREAD

**Issue by Samurais** [chatopera/cosin#205]
# 描述

很多用户反应这个问题

![image](https://user-images.githubusercontent.com/3538629/62517223-808f8400-b859-11e9-8d5e-da92a44254ca.png)

![image](https://user-images.githubusercontent.com/3538629/62517617-55596480-b85a-11e9-801e-7709b91c19f0.png)

## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by always-China** [comment]
## 优化开发环境CPU占用
春松客服 Disruptor 组件绑定CPU，占用100%资源，开发环境使用中会是开机器过热、卡顿，需要优化
### 方案
调整 Disruptor 等待策略
现在系统使用的是 SleepingWaitStrategy
希望在开发环境调整为 BlockingWaitStrategy
通过在 application.properties 设置一个选项，判断是否是开发环境，开发环境 使用 BlockingWaitStrategy，生产环境使用 SleepingWaitStrategy。

src/main/java/com/chatopera/cc/app/config/DisruptorConfigure.java

**Comment by always-China** [comment]
![image](https://user-images.githubusercontent.com/49581101/62517933-fa743d00-b85a-11e9-9903-ce0262fdaad4.png)
