### ISSUE TITLE
连接sql数据库错误

### ISSUE THREAD

**Issue by 96298li** [chatopera/cosin#207]
# 描述
### 使用docker搭建数据库
![image](https://user-images.githubusercontent.com/54433238/63574911-6d9be400-c5bb-11e9-9a18-4e9c216b8bd0.png)

### 连接数据库无表结构
![image](https://user-images.githubusercontent.com/54433238/63575084-ce2b2100-c5bb-11e9-8d04-425b8ef20e42.png)

### idea设置环境变量
![image](https://user-images.githubusercontent.com/54433238/63574981-9328ed80-c5bb-11e9-9c27-e290a6512c2d.png)

### 项目启动失败
![image](https://user-images.githubusercontent.com/54433238/63575032-ad62cb80-c5bb-11e9-810d-84cd23f4081d.png)

## 预期行为

# 解决方案

# 环境

开发环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
参考数据库[搭建文档](https://github.com/chatopera/cosin/wiki/%E6%98%A5%E6%9D%BE%E5%AE%A2%E6%9C%8D%EF%BC%9A%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83#%E6%95%B0%E6%8D%AE%E5%BA%93)，导入SQL文件。
