### ISSUE TITLE
[cc]加标签的下拉列表显示是否被选中的状态

### ISSUE THREAD

**Issue by wq11123** [chatopera/cosin#21]
# 描述

## 现在行为

![](https://user-images.githubusercontent.com/40993206/44778884-a2e04280-abb0-11e8-9c13-73809e7b610c.png)

## 预期行为
标签下拉列表中已选中的标签，显示为选中状态
# 解决方案

# 环境

* 代码版本:
The commit hash (`git rev-parse HEAD`)

**Comment by xianliwang** [comment]
已选中的标签，显示为选中状态
![image](https://user-images.githubusercontent.com/52594347/72601819-18d57d00-3951-11ea-91fb-838f24c3af41.png)
