### ISSUE TITLE
mvn 编译报错

### ISSUE THREAD

**Issue by TroubleJin** [chatopera/cosin#218]
# 描述
![image](https://user-images.githubusercontent.com/48788965/66994220-7e6e5f00-f0ff-11e9-8d96-48b7e6c9b061.png)

进入到contact-center/app 中mvn编译失败

**Comment by Samurais** [comment]
因为chatopera 的 maven repo的问题，这个我们这几天解决，感谢反馈！
我们解决后会关闭这个Issue。

**Comment by Samurais** [comment]
Chatopera mvn库访问已经正常。
