### ISSUE TITLE
部署到kubernetes后一直报错连接不到es

### ISSUE THREAD

**Issue by TroubleJin** [chatopera/cosin#219]
![image](https://user-images.githubusercontent.com/48788965/67485889-84cf7e80-f69d-11e9-8634-7200bcdf7b35.png)
但是es的状态是可用的。

**Comment by Samurais** [comment]
您的ES版本是多少？
ES的配置文件和春松客服默认的对比一下，另外连接端口是 discovery端口，不是9200.

所以，ES的配置参考 
[docker-compose.yml](https://github.com/chatopera/cosin/blob/develop/docker-compose.yml)

[elasticsearch.yml](https://github.com/chatopera/cosin/blob/develop/elasticsearch/config/elasticsearch.yml)
