### ISSUE TITLE
[cc]访客留言，空白文本也可以提交

### ISSUE THREAD

**Issue by wq11123** [chatopera/cosin#22]
# 描述

## 现在行为

![](https://user-images.githubusercontent.com/40993206/44777349-fcdf0900-abac-11e8-9f3a-0d82491d43ea.png)
无效数据给客服增加工作量
## 预期行为

# 解决方案

# 环境

* 代码版本:
The commit hash (`git rev-parse HEAD`)

**Comment by xianliwang** [comment]
@Samurais 坐席可以设置访客必填的留言内容字段

**Comment by xianliwang** [comment]
坐席可以自定义访客留言字段，设置后不会有空白留言
![image](https://user-images.githubusercontent.com/52594347/72602195-d52f4300-3951-11ea-96ff-96b8231c4b8c.png)
