### ISSUE TITLE
https部署文档

### ISSUE THREAD

**Issue by Samurais** [chatopera/cosin#220]
# 描述
配置HTTPS文档[地址](https://github.com/chatopera/cosin/wiki/%E7%A7%81%E6%9C%89%E9%83%A8%E7%BD%B2%E9%85%8D%E7%BD%AEHTTPS)。

如有问题在Issue内评论。

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by mukaiu** [comment]
基础知识
https://docs.docker.com/compose/
http://nginx.org/en/docs/http/configuring_https_servers.html
https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/

**Comment by Samurais** [comment]
CSDN博客介绍HTTPS和CDN配置
https://chatopera.blog.csdn.net/article/details/105820829

**Comment by ygcygc789789** [comment]
怎么我添加了ssl，就是无效。感觉好像nginx没启动。如何启动Nginx

**Comment by mukaiu** [comment]
看一下docker相关使用说明
