### ISSUE TITLE
新客服系统坐席分配涉

### ISSUE THREAD

**Issue by kongfanhua** [chatopera/cosin#223]
# 描述    新客服系统坐席分配，数据入库异常

## 预期行为  链接客服成功

# 解决方案 uk_agentuser，uk_agentservice两张表sessionid字段增加长度

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
需要由多少varchar增加到多少？

**Comment by kongfanhua** [comment]
目前是varchar32 ，新增到50，目前分配成功




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Samurais"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 下午5:39
收件人:&nbsp;"chatopera/cosin"<cosin@noreply.github.com&gt;;
抄送:&nbsp;"Saury"<5459514@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [chatopera/cosin] 新客服系统坐席分配涉 (#223)




需要由多少varchar增加到多少？

**Comment by Samurais** [comment]
这个问题的解决方案是修复sessionId，稍后提交变更。

# 为什么不改SQL
因为设计上，所有ID都是32长度。
