### ISSUE TITLE
从服务器部署方案来安装，出现docker权限问题

### ISSUE THREAD

**Issue by yetianyes** [chatopera/cosin#224]
# 描述
从服务器部署方案来安装，docker-compose 来启动没有启动起来，
在qq群里问了，说的是
”mysql, redis, elasticsearch, activemq这四个服务不正常导致了contact-center不正常“。

我看了日志发现这几个服务都是权限报错，所以过来问下，希望能够解决。

以下是报错信息：
我是centos7.6

## 现在行为
[root@localhost cosin]# docker-compose logs
Attaching to cskefu_nginx_1, cskefu_contact-center_1, cskefu_mysql_1, cskefu_activemq_1, cskefu_elasticsearch_1, cskefu_redis_1
nginx_1           | nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
nginx_1           | 2019/11/13 05:40:51 [emerg] 1#1: open() "/var/log/nginx/error.log" failed (13: Permission denied)
nginx_1           | nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
nginx_1           | 2019/11/13 05:40:53 [emerg] 1#1: open() "/var/log/nginx/error.log" failed (13: Permission denied)
nginx_1           | nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
nginx_1           | 2019/11/13 05:40:54 [emerg] 1#1: open() "/var/log/nginx/error.log" failed (13: Permission denied)
nginx_1           | nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
nginx_1           | 2019/11/13 05:40:55 [emerg] 1#1: open() "/var/log/nginx/error.log" failed (13: Permission denied)
nginx_1           | nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
nginx_1           | 2019/11/13 05:40:57 [emerg] 1#1: open() "/var/log/nginx/error.log" failed (13: Permission denied)
nginx_1           | nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
nginx_1           | 2019/11/13 05:41:00 [emerg] 1#1: open() "/var/log/nginx/error.log" failed (13: Permission denied)
contact-center_1  | 2019-11-13 13:40:50 connecting to mysql:3306/cosinee with root/****
elasticsearch_1   | chown: cannot read directory '/usr/share/elasticsearch/data': Permission denied
nginx_1           | nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
contact-center_1  | 2019-11-13 13:40:50 extract SQL script ...
nginx_1           | 2019/11/13 05:41:04 [emerg] 1#1: open() "/var/log/nginx/error.log" failed (13: Permission denied)
elasticsearch_1   | chown: cannot read directory '/usr/share/elasticsearch/data': Permission denied
contact-center_1  | 2019-11-13 13:40:54 start to import database ...
mysql_1           | chown: cannot read directory '/var/lib/mysql/': Permission denied
mysql_1           | chown: cannot read directory '/var/lib/mysql/': Permission denied
activemq_1        | chown: cannot read directory '/var/log/activemq': Permission denied
contact-center_1  | 2019-11-13 13:40:54 run MySQL DB initialize script ...
elasticsearch_1   | chown: cannot read directory '/usr/share/elasticsearch/data': Permission denied
nginx_1           | nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
mysql_1           | chown: cannot read directory '/var/lib/mysql/': Permission denied
activemq_1        | 2019-11-13 05:40:47,875 CRIT Supervisor running as root (no user in config file)
contact-center_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
elasticsearch_1   | chown: cannot read directory '/usr/share/elasticsearch/data': Permission denied
nginx_1           | 2019/11/13 05:41:11 [emerg] 1#1: open() "/var/log/nginx/error.log" failed (13: Permission denied)
redis_1           | 1:C 13 Nov 2019 05:40:46.849 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
mysql_1           | chown: cannot read directory '/var/lib/mysql/': Permission denied
activemq_1        | 2019-11-13 05:40:47,875 WARN Included extra file "/etc/supervisor/conf.d/activemq.conf" during parsing
elasticsearch_1   | chown: cannot read directory '/usr/share/elasticsearch/data': Permission denied
contact-center_1  | ERROR 2005 (HY000): Unknown MySQL server host 'mysql' (2)
redis_1           | 1:C 13 Nov 2019 05:40:46.849 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
mysql_1           | chown: cannot read directory '/var/lib/mysql/': Permission denied
activemq_1        | 2019-11-13 05:40:47,875 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
elasticsearch_1   | chown: cannot read directory '/usr/share/elasticsearch/data': Permission denied
contact-center_1  | Fail to resolve mysql database instance.
redis_1           | 1:C 13 Nov 2019 05:40:46.849 # Configuration loaded
mysql_1           | chown: cannot read directory '/var/lib/mysql/': Permission denied
elasticsearch_1   | chown: cannot read directory '/usr/share/elasticsearch/data': Permission denied
contact-center_1  | 2019-11-13 13:40:56 connecting to mysql:3306/cosinee with root/****
activemq_1        | 2019-11-13 05:40:47,902 INFO RPC interface 'supervisor' initialized
redis_1           | 1:M 13 Nov 2019 05:40:46.852 # Can't open the append-only file: Permission denied
mysql_1           | chown: cannot read directory '/var/lib/mysql/': Permission denied
elasticsearch_1   | chown: cannot read directory '/usr/share/elasticsearch/data': Permission denied
contact-center_1  | 2019-11-13 13:40:57 extract SQL script ...
activemq_1        | 2019-11-13 05:40:47,902 CRIT Server 'unix_http_server' running without any HTTP authentication checking
redis_1           | 1:C 13 Nov 2019 05:40:47.914 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
mysql_1           | chown: cannot read directory '/var/lib/mysql/': Permission denied
activemq_1        | 2019-11-13 05:40:47,903 INFO supervisord started with pid 1
redis_1           | 1:C 13 Nov 2019 05:40:47.914 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
contact-center_1  | 2019-11-13 13:41:01 start to import database ...
activemq_1        | 2019-11-13 05:40:48,908 INFO spawned: 'cron' with pid 18
redis_1           | 1:C 13 Nov 2019 05:40:47.914 # Configuration loaded
contact-center_1  | 2019-11-13 13:41:01 run MySQL DB initialize script ...
contact-center_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
redis_1           | 1:M 13 Nov 2019 05:40:47.917 # Can't open the append-only file: Permission denied
activemq_1        | 2019-11-13 05:40:48,913 INFO spawned: 'activemq' with pid 19
redis_1           | 1:C 13 Nov 2019 05:40:49.021 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1           | 1:C 13 Nov 2019 05:40:49.021 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
activemq_1        | 2019-11-13 05:40:49,997 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
activemq_1        | 2019-11-13 05:40:49,997 INFO success: activemq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redis_1           | 1:C 13 Nov 2019 05:40:49.021 # Configuration loaded
redis_1           | 1:M 13 Nov 2019 05:40:49.023 # Can't open the append-only file: Permission denied
redis_1           | 1:C 13 Nov 2019 05:40:50.370 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1           | 1:C 13 Nov 2019 05:40:50.370 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1           | 1:C 13 Nov 2019 05:40:50.370 # Configuration loaded
redis_1           | 1:M 13 Nov 2019 05:40:50.374 # Can't open the append-only file: Permission denied
redis_1           | 1:C 13 Nov 2019 05:40:52.370 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1           | 1:C 13 Nov 2019 05:40:52.370 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1           | 1:C 13 Nov 2019 05:40:52.370 # Configuration loaded
redis_1           | 1:M 13 Nov 2019 05:40:52.373 # Can't open the append-only file: Permission denied
redis_1           | 1:C 13 Nov 2019 05:40:55.080 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1           | 1:C 13 Nov 2019 05:40:55.081 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1           | 1:C 13 Nov 2019 05:40:55.081 # Configuration loaded
redis_1           | 1:M 13 Nov 2019 05:40:55.084 # Can't open the append-only file: Permission denied
redis_1           | 1:C 13 Nov 2019 05:40:59.149 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1           | 1:C 13 Nov 2019 05:40:59.149 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1           | 1:C 13 Nov 2019 05:40:59.149 # Configuration loaded
redis_1           | 1:M 13 Nov 2019 05:40:59.152 # Can't open the append-only file: Permission denied
redis_1           | 1:C 13 Nov 2019 05:41:06.393 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1           | 1:C 13 Nov 2019 05:41:06.393 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1           | 1:C 13 Nov 2019 05:41:06.393 # Configuration loaded
redis_1           | 1:M 13 Nov 2019 05:41:06.396 # Can't open the append-only file: Permission denied

## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
运行命令的权限不够，无法创建必须的目录。
使用 root或者 sudo。

比如:
```
sudo docker-compose up -d contact-center
```

**Comment by yetianyes** [comment]
好的

**Comment by yetianyes** [comment]
不好意思 试了很多遍还是不行。我是centos  root登陆

[root@localhost cosin]# sudo docker-compose up
Creating network "cskefu_default" with the default driver
Creating cskefu_redis_1         ... done
Creating cskefu_mysql_1         ... done
Creating cskefu_elasticsearch_1 ... done
Creating cskefu_activemq_1      ... done
Creating cskefu_contact-center_1 ... done
Creating cskefu_nginx_1          ... done
Attaching to cskefu_redis_1, cskefu_activemq_1, cskefu_elasticsearch_1, cskefu_mysql_1, cskefu_contact-center_1, cskefu_nginx_1
redis_1           | 1:C 13 Nov 2019 06:48:31.854 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1           | 1:C 13 Nov 2019 06:48:31.855 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1           | 1:C 13 Nov 2019 06:48:31.855 # Configuration loaded
redis_1           | 1:M 13 Nov 2019 06:48:31.857 # Can't open the append-only file: Permission denied
activemq_1        | chown: cannot read directory '/var/log/activemq': Permission denied
activemq_1        | 2019-11-13 06:48:32,835 CRIT Supervisor running as root (no user in config file)
activemq_1        | 2019-11-13 06:48:32,836 WARN Included extra file "/etc/supervisor/conf.d/activemq.conf" during parsing
activemq_1        | 2019-11-13 06:48:32,836 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
elasticsearch_1   | chown: cannot read directory '/usr/share/elasticsearch/data': Permission denied
activemq_1        | 2019-11-13 06:48:32,861 INFO RPC interface 'supervisor' initialized
activemq_1        | 2019-11-13 06:48:32,861 CRIT Server 'unix_http_server' running without any HTTP authentication checking
activemq_1        | 2019-11-13 06:48:32,862 INFO supervisord started with pid 1
contact-center_1  | 2019-11-13 14:48:35 connecting to mysql:3306/cosinee with root/****
contact-center_1  | 2019-11-13 14:48:35 extract SQL script ...
mysql_1           | chown: cannot read directory '/var/lib/mysql/': Permission denied
activemq_1        | 2019-11-13 06:48:33,865 INFO spawned: 'cron' with pid 17
activemq_1        | 2019-11-13 06:48:33,871 INFO spawned: 'activemq' with pid 18
activemq_1        | 2019-11-13 06:48:34,981 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
activemq_1        | 2019-11-13 06:48:34,981 INFO success: activemq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
nginx_1           | nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
nginx_1           | 2019/11/13 06:48:36 [emerg] 1#1: open() "/var/log/nginx/error.log" failed (13: Permission denied)
cskefu_elasticsearch_1 exited with code 1
cskefu_mysql_1 exited with code 1
cskefu_redis_1 exited with code 1
cskefu_nginx_1 exited with code 1
elasticsearch_1   | chown: cannot read directory '/usr/share/elasticsearch/data': Permission denied
mysql_1           | chown: cannot read directory '/var/lib/mysql/': Permission denied
contact-center_1  | 2019-11-13 14:48:39 start to import database ...
contact-center_1  | 2019-11-13 14:48:39 run MySQL DB initialize script ...
contact-center_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
contact-center_1  | ERROR 2005 (HY000): Unknown MySQL server host 'mysql' (2)
cskefu_nginx_1 exited with code 1
contact-center_1  | Fail to resolve mysql database instance.
contact-center_1  | 2019-11-13 14:48:41 connecting to mysql:3306/cosinee with root/****
cskefu_nginx_1 exited with code 1
elasticsearch_1   | chown: cannot read directory '/usr/share/elasticsearch/data': Permission denied
cskefu_elasticsearch_1 exited with code 1
mysql_1           | chown: cannot read directory '/var/lib/mysql/': Permission denied
contact-center_1  | 2019-11-13 14:48:42 extract SQL script ...
cskefu_mysql_1 exited with code 1
cskefu_nginx_1 exited with code 1
redis_1           | 1:M 13 Nov 2019 06:48:44.398 # Can't open the append-only file: Permission denied
cskefu_redis_1 exited with code 1
cskefu_nginx_1 exited with code 1
cskefu_elasticsearch_1 exited with code 1
contact-center_1  | 2019-11-13 14:48:46 start to import database ...
contact-center_1  | 2019-11-13 14:48:46 run MySQL DB initialize script ...
contact-center_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
contact-center_1  | ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (111)
contact-center_1  | Fail to resolve mysql database instance.
mysql_1           | chown: cannot read directory '/var/lib/mysql/': Permission denied
cskefu_contact-center_1 exited with code 1
cskefu_mysql_1 exited with code 1
contact-center_1  | 2019-11-13 14:48:47 connecting to mysql:3306/cosinee with root/****
contact-center_1  | 2019-11-13 14:48:47 extract SQL script ...
cskefu_nginx_1 exited with code 1
contact-center_1  | 2019-11-13 14:48:51 start to import database ...
contact-center_1  | 2019-11-13 14:48:51 run MySQL DB initialize script ...
contact-center_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
contact-center_1  | ERROR 2005 (HY000): Unknown MySQL server host 'mysql' (2)
contact-center_1  | Fail to resolve mysql database instance.
redis_1           | 1:C 13 Nov 2019 06:48:51.642 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1           | 1:C 13 Nov 2019 06:48:51.642 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1           | 1:C 13 Nov 2019 06:48:51.642 # Configuration loaded
redis_1           | 1:M 13 Nov 2019 06:48:51.645 # Can't open the append-only file: Permission denied
cskefu_contact-center_1 exited with code 1
cskefu_redis_1 exited with code 1
contact-center_1  | 2019-11-13 14:48:52 connecting to mysql:3306/cosinee with root/****
contact-center_1  | 2019-11-13 14:48:52 extract SQL script ...
elasticsearch_1   | chown: cannot read directory '/usr/share/elasticsearch/data': Permission denied
cskefu_elasticsearch_1 exited with code 1
mysql_1           | chown: cannot read directory '/var/lib/mysql/': Permission denied
cskefu_mysql_1 exited with code 1

**Comment by yetianyes** [comment]
8核16g ，centos 7.6

**Comment by Samurais** [comment]
```
redis_1 | 1:M 13 Nov 2019 06:48:31.857 # Can't open the append-only file: Permission denied
activemq_1 | chown: cannot read directory '/var/log/activemq': Permission denied
activemq_1 | 2019-11-13 06:48:32,835 CRIT Supervisor running as root (no user in config file)
activemq_1 | 2019-11-13 06:48:32,836 WARN Included extra file "/etc/supervisor/conf.d/activemq.conf" during parsing
activemq_1 | 2019-11-13 06:48:32,836 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
elasticsearch_1 | chown: cannot read directory '/usr/share/elasticsearch/data': Permission denied
activemq_1 | 2019-11-13 06:48:32,861 INFO RPC interface 'supervisor' initialized
activemq_1 | 2019-11-13 06:48:32,861 CRIT Server 'unix_http_server' running without any HTTP authentication checking
activemq_1 | 2019-11-13 06:48:32,862 INFO supervisord started with pid 1
contact-center_1 | 2019-11-13 14:48:35 connecting to mysql:3306/cosinee with root/****
contact-center_1 | 2019-11-13 14:48:35 extract SQL script ...
mysql_1 | chown: cannot read directory '/var/lib/mysql/': Permission denied
```

这几行已经说的很清楚了，就是权限的问题，无法创建出目录。
如果是root运行都无法解决，那就是在安装docker时，docker的启动的账号没有权限。

**Comment by yetianyes** [comment]
好的 我再试一下

**Comment by johnseed** [comment]
> 好的 我再试一下

请问您解决了吗，我也是同样的问题
