### ISSUE TITLE
连接坐席失败，在线咨询不可用

### ISSUE THREAD

**Issue by 2009jiaopeng** [chatopera/cosin#225]
# 描述
客服接入-网站列表，网站已经是创建好的http://localhost:8035/im/text/0rdj44.html
但是为什么访问网址的时候，一直是  ‘连接坐席失败，在线咨询不可用’
## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
客服的情况是什么样，有登录的就绪的客服吗？
在java控制台有什么日志？

**Comment by 2009jiaopeng** [comment]
客服也在线的，就是admin超级管理员
![QQ截图20191113152844](https://user-images.githubusercontent.com/57693453/68742127-56085080-062a-11ea-8a5a-82e25a72e001.png)

![U~M@M@_H7D6F4BGIIFCLQVQ](https://user-images.githubusercontent.com/57693453/68742221-94057480-062a-11ea-8ccd-e2703eb22289.png)

![A6G7CWWB%@@ X``B T}DI%1](https://user-images.githubusercontent.com/57693453/68742256-ac758f00-062a-11ea-96bb-2b02dafdef46.png)

![W4RAS2W@PBREGDQ6V(@TMQR](https://user-images.githubusercontent.com/57693453/68742293-c911c700-062a-11ea-9af6-d5da59fcc631.png)

![VYIIYNEGJ1R%Y0}$JV2L$Q3](https://user-images.githubusercontent.com/57693453/68742328-dfb81e00-062a-11ea-949b-fd1474c421e5.png)

我按照官方文档上面操作的，但是进网址发消息的时候一直报这个坐席连接失败，是不是有什么地方还需要配置呀

**Comment by Samurais** [comment]
拉取最新的代码，该问题在昨天的提交中有解决。

**Comment by 2009jiaopeng** [comment]
好的
