### ISSUE TITLE
运行时，后台报错

### ISSUE THREAD

**Issue by fumaobin** [chatopera/cosin#226]
# 描述
运行环境时，后台一直报下面的错误
contact-center_1  | 2019-11-13 16:29:21.736 INFO  c.c.cc.aop.OnlineUserAspect - [save] put onlineUser id fc0e062d324d5782b5b5a7a73d444d43, status online, invite status default [http-nio-8035-exec-3] 
contact-center_1  | 2019-11-13 16:29:21.809 INFO  c.c.c.h.apps.IMController - [point] session snsid 0nn0uv, session 4306759212104a2698e07d4b393576f2 [http-nio-8035-exec-6] 
contact-center_1  | 2019-11-13 16:29:21.809 INFO  c.c.c.h.apps.IMController - [point] new website is : 10.1.6.140 [http-nio-8035-exec-6] 
contact-center_1  | 2019-11-13 16:29:21.841 INFO  c.c.c.h.apps.IMController - [point] find CousultInvite 2c9280866e6351c4016e636ebe1d0010 [http-nio-8035-exec-6] 
contact-center_1  | 2019-11-13 16:29:25.038 INFO  c.c.cc.aop.OnlineUserAspect - [save] put onlineUser id fc0e062d324d5782b5b5a7a73d444d43, status online, invite status default [http-nio-8035-exec-5] 
contact-center_1  | 2019-11-13 16:29:25.094 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] threw exception [http-nio-8035-exec-11] 
contact-center_1  | java.lang.NullPointerException: null
contact-center_1  |     at com.chatopera.cc.proxy.UserProxy.attachOrgansPropertiesForUser(UserProxy.java:548)
contact-center_1  |     at com.chatopera.cc.interceptor.UserInterceptorHandler.preHandle(UserInterceptorHandler.java:58)
contact-center_1  |     at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:133)
contact-center_1  |     at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:962)
contact-center_1  |     at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
contact-center_1  |     at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
contact-center_1  |     at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
contact-center_1  |     at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
contact-center_1  |     at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
contact-center_1  |     at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
contact-center_1  |     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
contact-center_1  |     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
contact-center_1  |     at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
contact-center_1  |     at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:469)
contact-center_1  |     at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:392)
contact-center_1  |     at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:311)
contact-center_1  |     at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:395)
contact-center_1  |     at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:254)
contact-center_1  |     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:177)
contact-center_1  |     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
contact-center_1  |     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
contact-center_1  |     at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
contact-center_1  |     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
contact-center_1  |     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
contact-center_1  |     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
contact-center_1  |     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
contact-center_1  |     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
contact-center_1  |     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
contact-center_1  |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
contact-center_1  |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
contact-center_1  |     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
contact-center_1  |     at java.lang.Thread.run(Thread.java:748)
contact-center_1  | 2019-11-13 16:29:25.095 ERROR o.a.c.c.C.[Tomcat].[localhost] - Exception Processing ErrorPage[errorCode=0, location=/error] [http-nio-8035-exec-11] 
contact-center_1  | org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
contact-center_1  |     at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
contact-center_1  |     at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
contact-center_1  |     at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
contact-center_1  |     at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
contact-center_1  |     at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
contact-center_1  |     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
contact-center_1  |     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
contact-center_1  |     at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
contact-center_1  |     at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:469)
contact-center_1  |     at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:392)
contact-center_1  |     at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:311)
contact-center_1  |     at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:395)
contact-center_1  |     at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:254)
contact-center_1  |     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:177)
contact-center_1  |     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
contact-center_1  |     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
contact-center_1  |     at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
contact-center_1  |     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
contact-center_1  |     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
contact-center_1  |     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
contact-center_1  |     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
contact-center_1  |     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
contact-center_1  |     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
contact-center_1  |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
contact-center_1  |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
contact-center_1  |     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
contact-center_1  |     at java.lang.Thread.run(Thread.java:748)
contact-center_1  | Caused by: java.lang.NullPointerException: null
contact-center_1  |     at com.chatopera.cc.proxy.UserProxy.attachOrgansPropertiesForUser(UserProxy.java:548)
contact-center_1  |     at com.chatopera.cc.interceptor.UserInterceptorHandler.preHandle(UserInterceptorHandler.java:58)
contact-center_1  |     at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:133)
contact-center_1  |     at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:962)
contact-center_1  |     at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
contact-center_1  |     at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
contact-center_1  |     ... 26 common frames omitted
## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
您能描述一下部署方式么？
是使用我们的私有部署脚本还是自己的？contact-center启动后，会有如下的日志：
![image](https://user-images.githubusercontent.com/3538629/68747133-e350a280-0634-11ea-8b07-2dd2a7826bf1.png)


您能发布一下build后的字符串吗？这个是版本号，我们检查一下

**Comment by fumaobin** [comment]
用的你们的私有部署，版本应该时PLACEHOLDER这个吧  
春松客服: 多渠道智能客服 vPLACEHOLDER build PLACEHOLDER

**Comment by Samurais** [comment]
私有部署也可以用我们的docker，私有部署参考文档：[私有部署文档](https://github.com/chatopera/cosin/wiki/%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%83%A8%E7%BD%B2#%E5%8D%95%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%83%A8%E7%BD%B2)

**Comment by Samurais** [comment]
这个问题现在解决了吗？后来根本原因是什么？

**Comment by fumaobin** [comment]
不知道，突然又没这个问题了。
