### ISSUE TITLE
更新的项目，添加新用户时，提交返回失败，保存不了数据

### ISSUE THREAD

**Issue by 2009jiaopeng** [chatopera/cosin#228]
# 描述
![40 WQ XGC3D)6D(`RH8R`HT](https://user-images.githubusercontent.com/57693453/68751429-8953db00-063c-11ea-86c4-4e3fb2be7071.png)

## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
部署方式是什么？是用我们发布的docker容器么？
还是自己搭建的开发环境？
如果是自己搭建的开发环境，拉取最新的代码。

**Comment by 2009jiaopeng** [comment]
我是自己搭的开发环境，今天又更新代码了吗

**Comment by Samurais** [comment]
今天更新，但是看上去您的代码不是最新的。
按照最新的代码逻辑，返回 AUTH_ERROR 会跳转到登录。






------------------
Cheers.
Hai Liang Wang, CEO, Chatopera




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by 2009jiaopeng** [comment]
![IN8{S%)L_SDRFWMQNO CXP](https://user-images.githubusercontent.com/57693453/68752166-cc627e00-063d-11ea-86f9-268a7799627a.png)

今天下午更新的代码是这样的，我再更新下试试

**Comment by Samurais** [comment]
该问题使用最新代码是否已经解决？
