### ISSUE TITLE
contactcenter 无法打开

### ISSUE THREAD

**Issue by yetianyes** [chatopera/cosin#229]
# 描述
contactcenter 无法打开
下面是log，有一个IP172.18.0.6比较诡异，麻烦看下

[root@localhost cosin]# docker-compose logs -f contact-center
Attaching to cskefu_contact-center_1
contact-center_1  | 2019-11-13 18:48:31 connecting to mysql:3306/cosinee with root/****
contact-center_1  | 2019-11-13 18:48:31 extract SQL script ...
contact-center_1  | 2019-11-13 18:48:34 start to import database ...
contact-center_1  | 2019-11-13 18:48:34 run MySQL DB initialize script ...
contact-center_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
contact-center_1  | ERROR 1045 (28000): Access denied for user 'root'@'172.18.0.6' (using password: YES)
contact-center_1  | Fail to resolve mysql database instance.
contact-center_1  | 2019-11-13 18:48:35 connecting to mysql:3306/cosinee with root/****
contact-center_1  | 2019-11-13 18:48:35 extract SQL script ...
contact-center_1  | 2019-11-13 18:48:37 start to import database ...
contact-center_1  | 2019-11-13 18:48:37 run MySQL DB initialize script ...
contact-center_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
contact-center_1  | ERROR 1045 (28000): Access denied for user 'root'@'172.18.0.6' (using password: YES)
contact-center_1  | Fail to resolve mysql database instance.
contact-center_1  | 2019-11-13 18:48:38 connecting to mysql:3306/cosinee with root/****
contact-center_1  | 2019-11-13 18:48:38 extract SQL script ...
contact-center_1  | 2019-11-13 18:48:41 start to import database ...
contact-center_1  | 2019-11-13 18:48:41 run MySQL DB initialize script ...
contact-center_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
contact-center_1  | ERROR 1045 (28000): Access denied for user 'root'@'172.18.0.6' (using password: YES)
contact-center_1  | Fail to resolve mysql database instance.
contact-center_1  | 2019-11-13 18:48:42 connecting to mysql:3306/cosinee with root/****
contact-center_1  | 2019-11-13 18:48:42 extract SQL script ...
contact-center_1  | 2019-11-13 18:48:46 start to import database ...
contact-center_1  | 2019-11-13 18:48:46 run MySQL DB initialize script ...
contact-center_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
contact-center_1  | ERROR 1045 (28000): Access denied for user 'root'@'172.18.0.6' (using password: YES)
contact-center_1  | Fail to resolve mysql database instance.
contact-center_1  | 2019-11-13 18:48:48 connecting to mysql:3306/cosinee with root/****
contact-center_1  | 2019-11-13 18:48:48 extract SQL script ...
contact-center_1  | 2019-11-13 18:48:52 start to import database ...
contact-center_1  | 2019-11-13 18:48:52 run MySQL DB initialize script ...
contact-center_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
contact-center_1  | ERROR 1045 (28000): Access denied for user 'root'@'172.18.0.6' (using password: YES)
contact-center_1  | Fail to resolve mysql database instance.
contact-center_1  | 2019-11-13 18:48:54 connecting to mysql:3306/cosinee with root/****
contact-center_1  | 2019-11-13 18:48:54 extract SQL script ...
contact-center_1  | 2019-11-13 18:48:58 start to import database ...
contact-center_1  | 2019-11-13 18:48:58 run MySQL DB initialize script ...
contact-center_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
contact-center_1  | ERROR 1045 (28000): Access denied for user 'root'@'172.18.0.6' (using password: YES)
contact-center_1  | Fail to resolve mysql database instance.
cskefu_contact-center_1 exited with code 1

## 现在行为
docker无法打开
## 预期行为
可以正常打开
# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
MySQL数据库链接失败。
查看 docker-compose.yml中有关MySQL连接的定义：

```
SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cosinee?useUnicode=true&characterEncoding=UTF-8
SPRING_DATASOURCE_USERNAME=root
SPRING_DATASOURCE_PASSWORD=${DB_PASSWD:-123456}
```

其中 DB_PASSWD 定义在 .env 文件中。

对于，SPRING_DATASOURCE_URL，这个字符串的格式一定是```jdbc:mysql://$MYSQL_IP:$MYSQL_PORT/cosinee?useUnicode=true&characterEncoding=UTF-8```

如果从docker-compose部署，按照我们文档操作。
如果是你用其它部署方式，以上设置为环境变量。

**Comment by yetianyes** [comment]
你这两个字符串就不一致啊，SPRING_DATASOURCE_URL
选择下面那个？？？？

**Comment by yetianyes** [comment]
这个是docker-compose.yml 文件

version: "3"
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/certs
    depends_on:
      - contact-center

  contact-center:
    image: chatopera/contact-center:develop
    restart: always
    ports:
      - "${CC_WEB_PORT:-8035}:8035"
      - "${CC_SOCKET_PORT:-8036}:8036"
    volumes:
      - ./contact-center/data:/data
      - ./contact-center/logs:/logs
    environment:
      - JAVA_OPTS=-Xmx12288m -Xms2048m -XX:PermSize=256m -XX:MaxPermSize=1024m -Djava.net.preferIPv4Stack=true
      - SERVER_PORT=8035
      - SERVER_LOG_PATH=/logs
      - SERVER_LOG_LEVEL=${LOG_LEVEL:-WARN}
      - WEB_UPLOAD_PATH=/data
      - SPRING_FREEMARKER_CACHE=true
      - SPRING_DATA_ELASTICSEARCH_PROPERTIES_PATH_DATA=/data
      - UK_IM_SERVER_PORT=8036
      - UK_IM_SERVER_HOST=localhost
      - UK_IM_SERVER_THREADS=10
      # set a separated port for SSL
      - CS_IM_SERVER_SSL_PORT=${CC_SOCKET_PORT:-8036}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cosinee?useUnicode=true&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWD:-123456}
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=${DB_PASSWD:-123456}
      - SPRING_DATA_ELASTICSEARCH_CLUSTER_NAME=elasticsearch
      - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq:61616
      - CSKEFU_MODULE_CALLOUT=false
      - CSKEFU_MODULE_CONTACTS=true
      - CSKEFU_MODULE_CHATBOT=true
      - SKYPE_CHANNEL_CRM=${SKYPE_CHANNEL_CRM:-placeholder}
    depends_on:
      - mysql
      - redis
      - elasticsearch
      - activemq

  activemq:
    image: chatopera/activemq:5.14.3
    restart: always
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=${DB_PASSWD:-123456}
      - ACTIVEMQ_ENABLED_SCHEDULER=true
      - ACTIVEMQ_MIN_MEMORY=1024
      - ACTIVEMQ_MAX_MEMORY=4096
    volumes:
      - ./database/activemq/data:/data
      - ./database/activemq/logs:/var/log/activemq
    ports:
      - "${ACTIVEMQ_PORT1:-8051}:8161"
      - "${ACTIVEMQ_PORT2:-8052}:61616"
      - "${ACTIVEMQ_PORT3:-8053}:61613"

  mysql:
    image: chatopera/mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWD:-123456}
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=${DB_PASSWD:-123456}
    ports:
      - "${MYSQL_PORT:-8037}:3306"
    volumes:
      - ./database/mysql/data:/var/lib/mysql
    command: --max_allowed_packet=32505856

  redis:
    image: chatopera/redis:5.0.5
    environment:
      - REDIS_PASSWORD=${DB_PASSWD:-123456}
    restart: always
    volumes:
      - ./database/redis/data:/data
    ports:
      - "${REDIS_PORT:-8041}:6379"

  elasticsearch:
    image: elasticsearch:2.4.6
    restart: always
    volumes:
      - ./database/elasticsearch/data:/usr/share/elasticsearch/data
      - ./database/elasticsearch/config:/usr/share/elasticsearch/config
      - ./database/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    ports:
      - "${ES_PORT1:-8039}:9200"
      - "${ES_PORT2:-8040}:9300"

**Comment by yetianyes** [comment]
严格按照你们的格式来安装的

**Comment by Samurais** [comment]
就是这样？
```
git clone https://github.com/chatopera/cosin.git
cd cosin
cp sample.env .env # 使用文本编辑器打开 .env 文件，并按照需求需改配置
```
最后的 .env 文件也修改了吧？

**Comment by yetianyes** [comment]
最后执行了 
cp sample.env .env # 使用文本编辑器打开 .env 文件，并按照需求需改配置

但是没有编辑什么

**Comment by yetianyes** [comment]
这个是 cosin文件下的  .env文件

COMPOSE_FILE=docker-compose.yml
COMPOSE_PROJECT_NAME=cskefu
MYSQL_PORT=8037
REDIS_PORT=8041
ES_PORT1=8039
ES_PORT2=8040
CC_WEB_PORT=8035
CC_SOCKET_PORT=8036
ACTIVEMQ_PORT1=8051
ACTIVEMQ_PORT2=8052
ACTIVEMQ_PORT3=8053
DB_PASSWD=ac402bd86191d959
LOG_LEVEL=INFO

**Comment by yetianyes** [comment]
我看了下 应该是mysql 的 地址有问题 ，是否是contact-center 中 SPRING_DATASOURCE_URL，获取的url 有问题。需要我提供什么吗？

**Comment by Samurais** [comment]
可能是防火墙的原因，建议将系统防火墙关闭后试试。

**Comment by Samurais** [comment]
```
systemctl disable firewalld
systemctl stop firewalld
```
https://www.centos.bz/2018/01/centos-7-docker-%E9%98%B2%E7%81%AB%E5%A2%99%E7%AE%80%E5%8D%95%E9%85%8D%E7%BD%AE/

**Comment by yetianyes** [comment]
sorry 不是   安装到时候就全部关闭，现在试了一遍还是不行。我重新安装一次好了 ，麻烦了
