### ISSUE TITLE
颜色变更时，按钮变更无效

### ISSUE THREAD

**Issue by fumaobin** [chatopera/cosin#230]
# 描述
控制台改变用户前端颜色时，按钮的颜色不发生变化。
提交[公司信息说明](http://chatopera.mikecrm.com/lVtMuGN)后优先处理解决！

## 预期行为

# 解决方案

# 环境

- 代码版本:
  Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
请填写表格：http://chatopera.mikecrm.com/lVtMuGN
填写好后我们会尽快答疑。

**Comment by fumaobin** [comment]
![image](https://user-images.githubusercontent.com/57658737/69299474-962f8a80-0c4b-11ea-8e8b-a113ce80bcc3.png)
按钮的颜色改不了

**Comment by Samurais** [comment]
设计如此。

**Comment by hailiang-wang** [comment]
该问题是 BUG，现已经修正。
https://github.com/cskefu/cskefu/issues/807
