### ISSUE TITLE
用户发来的会话找不到，是管理员创建的子用户

### ISSUE THREAD

**Issue by Zct-123** [chatopera/cosin#231]
![4 76 1DMMG5R}657 _E(CMY](https://user-images.githubusercontent.com/57829156/68991361-07142280-0899-11ea-9a44-db9344207337.png)

**Comment by Samurais** [comment]
为该子账号设置权限。
过程：
角色 - 授予坐席工作台，联系人和客户。
组织机构 - 根据公司情况，至少设立一个组织机构。

把该账号关联到角色和组织机构。

针对于系统的使用和二次开发，我们最近会推出一个培训课程，请填一下表格，以便获取该信息。
[表格地址](http://chatopera.mikecrm.com/lVtMuGN)

**Comment by Samurais** [comment]
另外，在文档中心中也有一些知识，在使用系统前需要先阅读。
https://docs.chatopera.com/products/cskefu/index.html
