### ISSUE TITLE
加上https后客服对话就发不出去了

### ISSUE THREAD

**Issue by hzg-java** [chatopera/cosin#233]
添加https协议和域名代理后客服端和访客端对话都无法发出，系统其它功能都正常；
环境：
    docker部署

**Comment by Samurais** [comment]
请详细描述配置HTTPS的过程，在配置前阅读文档，连接在下面的Issue中。

https://github.com/chatopera/cosin/issues/220

**Comment by mukaiu** [comment]
CC_SOCKET_PORT 未配置正确

**Comment by Samurais** [comment]
参考 https://github.com/chatopera/cosin/issues/236 最后的评论，修改一下docker-compose.yml
