### ISSUE TITLE
https配置后，依然无效，急急急！！！

### ISSUE THREAD

**Issue by fumaobin** [chatopera/cosin#234]
# 描述
急急急！！！
我按部署文档配置了https后，用https访问依然不行。

部署文件如下：
```
server {
    listen 443 ssl;
    server_name czgx.smarts.online;
    root /usr/share/nginx/html;
    client_max_body_size 100M;

    ssl_certificate /certs/1658241__smarts.online.pem;
    ssl_certificate_key /certs/1658241__smarts.online.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://contact-center:8035; 
    }

    location /socket.io { proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_http_version 1.1;
    proxy_pass http://contact-center:8036; 
    }
}
```
版本：多渠道智能客服 v5.0.0 build 2633da2

访问地址：https://47.93.249.110:8035/login.html,不带s是可以的

**Comment by Samurais** [comment]
执行
```
docker-compose ps
```
查看各服务状态。

查看nginx日志
```
docker-compose logs -f nginx
```

确定nginx容器可以访问contact-center
```
docker-compose exec nginx bash
登录后执行 ping contact-center
```
如果nginx容器没有ping命令，先安装 ping
然后DNS解析设置的域名到IP保证没有问题。

**Comment by fumaobin** [comment]
docker-compose ps下没有nginx的相关信息。。日志什么都没有

**Comment by fumaobin** [comment]
nginx 没法启动。。

root@iZ2ze9z5o9dc8y2mj77uweZ:/home/service/cosin# docker-compose up -d nginx
cskefu_elasticsearch_1 is up-to-date
cskefu_redis_1 is up-to-date
cskefu_activemq_1 is up-to-date
cskefu_mysql_1 is up-to-date
cskefu_contact-center_1 is up-to-date
Starting cskefu_nginx_1 ... error

ERROR: for cskefu_nginx_1  Cannot start service nginx: driver failed programming external connectivity on endpoint cskefu_nginx_1 (cce9c93f84d25e032216b402c19fa7305c784f028a0fa61e3c072efaf47da4d0): Bind for 0.0.0.0:443 failed: port is already allocated

ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint cskefu_nginx_1 (cce9c93f84d25e032216b402c19fa7305c784f028a0fa61e3c072efaf47da4d0): Bind for 0.0.0.0:443 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

**Comment by Samurais** [comment]
宿主服务器的端口80和443被其它程序占用了。

**Comment by Samurais** [comment]
你好，你们的使用情况帮忙填写一下。http://chatopera.mikecrm.com/lVtMuGN

**Comment by fumaobin** [comment]
只要是contact-center已启动，就会占用端口，就没法启动nginx了，这是怎么回事。。我弄完这个就填

**Comment by fumaobin** [comment]
好了，端口配错了
