### ISSUE TITLE
访客端在IE浏览器下不显示，麻烦帮看一下

### ISSUE THREAD

**Issue by captain36** [chatopera/cosin#235]
5.0.0最新代码版本，
win10，IE11

**Comment by captain36** [comment]
浏览器报错信息  SCRIPT70: 没有权限

**Comment by Samurais** [comment]
请贴一下图片，服务部署地址和访客端地址，浏览器内报错的图片

**Comment by mukaiu** [comment]
![image](https://user-images.githubusercontent.com/7746790/69111887-de1ea800-0ab9-11ea-9f28-826d291b74d6.png)

**Comment by mukaiu** [comment]
IE安全设置默认禁止跨域

**Comment by Samurais** [comment]
在Windows上，可以用默认带有的 Edge浏览器。
或者安装Chrome浏览器。
**如果是客服聊天空间的域名和春松客服的域名是相同的，则不会出现类似问题。**
很遗憾，其它方法，浏览器渠道就不支持IE浏览器了。
