### ISSUE TITLE
服务都能正常启动，https就是无法访问

### ISSUE THREAD

**Issue by hzg-java** [chatopera/cosin#236]
1、default.conf
server {
    listen 443 ssl;
    server_name xxxx.9win.shop;
    root /usr/share/nginx/html;
    client_max_body_size 100M;

    ssl_certificate /certs/2264826__9win.shop.pem;
    ssl_certificate_key /certs/2264826__9win.shop.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://contact-center:8035; 
    }

    location /socket.io { proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_http_version 1.1;
    proxy_pass http://contact-center:8036; 
    }
}
2、修改 .env 设置 CC_SOCKET_PORT=443，然后重启项目;
3、docker都正常启动
![8A$PYT4 I TP%L}GEI1HR_X](https://user-images.githubusercontent.com/57212161/69109062-7fedc700-0ab1-11ea-9753-4bc67dc32c6d.png)

**Comment by mukaiu** [comment]
日志了？

**Comment by hzg-java** [comment]
我刚才改了https的配置后能正常访问了，但是访客端的webSocket报错
![JV8P4OS5MT97AH@6@8@O6KX](https://user-images.githubusercontent.com/57212161/69110511-00162b80-0ab6-11ea-93f0-17269585c144.png)

**Comment by mukaiu** [comment]
CC_SOCKET_PORT 未配置

**Comment by Samurais** [comment]
配置HTTPS需要详细阅读文档。
https://github.com/chatopera/cosin/wiki/%E7%A7%81%E6%9C%89%E9%83%A8%E7%BD%B2%E9%85%8D%E7%BD%AEHTTPS

**Comment by hzg-java** [comment]
![3 F)~ A{71AT_5SF3N6$AW4](https://user-images.githubusercontent.com/57212161/69111775-8b44f080-0ab9-11ea-9d4d-88d40748fd38.png)

**Comment by hzg-java** [comment]
是CC_SOCKET_PORT设置成443没生效吗？

**Comment by mukaiu** [comment]
从log上看，是未生效
docker-compose down
docker-compose up -d
再试试

**Comment by fumaobin** [comment]
不行，会报端口冲突的错误。nginx 和contact-center不能同时起了。

root@iZ2ze9z5o9dc8y2mj77uweZ:/home/service/cosin# docker-compose up -d
Creating network "cskefu_default" with the default driver
Creating cskefu_mysql_1         ... done
Creating cskefu_elasticsearch_1 ... done
Creating cskefu_activemq_1      ... done
Creating cskefu_redis_1         ... done
Creating cskefu_contact-center_1 ... done
Creating cskefu_nginx_1          ... error

ERROR: for cskefu_nginx_1  Cannot start service nginx: driver failed programming external connectivity on endpoint cskefu_nginx_1 (25c8c85c2e54941de4d18604bb8df1230d95e676702ad1d2a898245dc7b30e0b): Bind for 0.0.0.0:443 failed: port is already allocated

ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint cskefu_nginx_1 (25c8c85c2e54941de4d18604bb8df1230d95e676702ad1d2a898245dc7b30e0b): Bind for 0.0.0.0:443 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

**Comment by Samurais** [comment]
嗯，这里我们发布的docker-compose.yml内容有问题，我稍后更新一下。
感谢反馈！

**Comment by Samurais** [comment]
https://github.com/chatopera/cosin/blob/osc/docker-compose.yml#L21,L22

**Comment by Samurais** [comment]
duplicated with #234

**Comment by Samurais** [comment]
在最新的代码中已经修改了docker-compose.yml配置。
