### ISSUE TITLE
docker镜像更新重启后数据库清空

### ISSUE THREAD

**Issue by hzg-java** [chatopera/cosin#238]
docker镜像更新重启后数据库清空，挂载的数据库文件还在，数据怎么恢复？

**Comment by Samurais** [comment]
使用最新的代码试一下，本周日的脚本有问题，每次更新请现在测试环境执行，备份cosin目录。
给您带来的不便深表歉意，我们将避免以后类似事情发生。
另外，数据丢失的问题，我们并不清楚，因为周日的更新没有删除数据的操作。
