### ISSUE TITLE
tag=V3.10.0版本中集成机器人总是失败

### ISSUE THREAD

**Issue by GangTimes** [chatopera/cosin#241]
# 描述

提交[公司信息说明](http://chatopera.mikecrm.com/lVtMuGN)后优先处理解决！

## 现在行为
![图片](https://user-images.githubusercontent.com/21360838/70305740-1f47e380-1840-11ea-9ec6-5a1756cd5abe.png)
通过调试，发现，在调用我在开发者平台上创建的机器人客服的时候，调用机器人RestAPI返回的结果为
"rc" -> {Integer@21553} 1
"error" -> "invalid timestamp."
正是这个原因导致无法创建机器人
## 预期行为
成功创建机器人

# 解决方案

# 环境

- 代码版本:
  Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
3.9.0版本不再维护。
