### ISSUE TITLE
tag=V5.0.0中运行失败问题

### ISSUE THREAD

**Issue by GangTimes** [chatopera/cosin#242]
# 描述

提交[公司信息说明](http://chatopera.mikecrm.com/lVtMuGN)后优先处理解决！

## 现在行为
###以下是新版本中的mysql配置
  mysql:
    image: chatopera/mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWD:-123456}
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=${DB_PASSWD:-123456}
    ports:
      - "${MYSQL_PORT:-8037}:3306"
    volumes:
      - ./database/mysql/data:/var/lib/mysql
    command: --max_allowed_packet=32505856
###以下是老版本的mysql配置
mysql:
    image: "mysql:5.6"
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=123456
     - MYSQL_DATABASE=contactcenter
     - MYSQL_USER=admin
     - MYSQL_PASSWORD=admin123456
    ports:
     - "8037:3306"
    volumes:
     - $PWD/mysql/data:/var/lib/mysql
     - $PWD/mysql/config:/etc/mysql
     - $PWD/contact-center/config/sql/cskefu-MySQL-slim.sql:/docker-entrypoint-initdb.d/0.cskefu-MySQL-slim.sql
    command: --max_allowed_packet=32505856

新版本的mysql服务连接失败，如果更换为旧版本的mysql服务（修改数据库名称）则可以正常运行。
即使修正了mysql配置的问题。还有redis配置也有问题。异常如下
JedisDataException: NOAUTH Authentication required.

## 预期行为
能够正常启动和使用
# 解决方案

# 环境

- 代码版本:
  Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
请参考部署方案重新部署5.0.0版本，5.0.0和3.9.0的数据库不兼容。
https://github.com/chatopera/cosin/wiki/%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%83%A8%E7%BD%B2
