### ISSUE TITLE
智能客服转人工客服报错连接坐席失败，在线咨询服务不可用

### ISSUE THREAD

**Issue by ynpang** [chatopera/cosin#244]
contact-center_1  | java.lang.IllegalArgumentException: null
contact-center_1  | 	at com.chatopera.cc.basic.MainContext$AgentUserStatusEnum.toValue(MainContext.java:927)
contact-center_1  | 	at com.chatopera.cc.acd.middleware.visitor.ACDVisServiceMw.apply(ACDVisServiceMw.java:52)
contact-center_1  | 	at com.chatopera.cc.acd.middleware.visitor.ACDVisServiceMw.apply(ACDVisServiceMw.java:34)
contact-center_1  | 	at com.chatopera.compose4j.Composer$1.apply(Composer.java:45)
contact-center_1  | 	at com.chatopera.cc.acd.middleware.visitor.ACDVisSessionCfgMw.apply(ACDVisSessionCfgMw.java:74)
contact-center_1  | 	at com.chatopera.cc.acd.middleware.visitor.ACDVisSessionCfgMw.apply(ACDVisSessionCfgMw.java:36)
contact-center_1  | 	at com.chatopera.compose4j.Composer$1.apply(Composer.java:45)
contact-center_1  | 	at com.chatopera.cc.acd.middleware.visitor.ACDVisBindingMw.apply(ACDVisBindingMw.java:86)
contact-center_1  | 	at com.chatopera.cc.acd.middleware.visitor.ACDVisBindingMw.apply(ACDVisBindingMw.java:32)
contact-center_1  | 	at com.chatopera.compose4j.Composer$1.apply(Composer.java:45)
contact-center_1  | 	at com.chatopera.cc.acd.middleware.visitor.ACDVisBodyParserMw.apply(ACDVisBodyParserMw.java:126)
contact-center_1  | 	at com.chatopera.cc.acd.middleware.visitor.ACDVisBodyParserMw.apply(ACDVisBodyParserMw.java:42)
contact-center_1  | 	at com.chatopera.compose4j.Composer.handle(Composer.java:50)
contact-center_1  | 	at com.chatopera.cc.acd.ACDVisitorDispatcher.enqueue(ACDVisitorDispatcher.java:99)
contact-center_1  | 	at com.chatopera.cc.socketio.handler.IMEventHandler.onConnect(IMEventHandler.java:157)
contact-center_1  | 	at sun.reflect.GeneratedMethodAccessor1517.invoke(Unknown Source)
contact-center_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
contact-center_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
contact-center_1  | 	at com.corundumstudio.socketio.annotation.OnConnectScanner$1.onConnect(OnConnectScanner.java:40)
contact-center_1  | 	at com.corundumstudio.socketio.namespace.Namespace.onConnect(Namespace.java:211)
contact-center_1  | 	at com.corundumstudio.socketio.handler.PacketListener.onPacket(PacketListener.java:87)
contact-center_1  | 	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:92)
contact-center_1  | 	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:36)
contact-center_1  | 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
contact-center_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
contact-center_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)

**Comment by Samurais** [comment]
使用最新代码，已经解决此问题。
* 解决机器人客服转人工时的错误
* 修正没有机器人客服，依然能看到“智能客服”的问题
https://github.com/chatopera/cosin/commit/6abacc646ec446060d9b6d5475bdb09abe9f17fa
