### ISSUE TITLE
部分依赖无法install成功

### ISSUE THREAD

**Issue by 15716597991** [chatopera/cosin#246]
代码从库上拉下来，导入idea，安装亚马逊jdk1.8，install出现下面问题：
![image](https://user-images.githubusercontent.com/53402282/70858603-dd095b00-1f3f-11ea-90cf-233419c20b12.png)
找不到相关依赖！求解答

**Comment by wtn001** [comment]
你现在装好了吗？

**Comment by Samurais** [comment]
# duplicated with #250
