### ISSUE TITLE
客服系统经常崩溃

### ISSUE THREAD

**Issue by captain36** [chatopera/cosin#247]
# 描述
最新代码，发现客服系统经常崩溃，有getAgentReport方法疑似死循环执行
![图片](https://user-images.githubusercontent.com/7778643/70884782-ee229c80-2011-11ea-8575-acd9c1296a99.png)

提交[公司信息说明](http://chatopera.mikecrm.com/lVtMuGN)后优先处理解决！

## 预期行为

# 解决方案

# 环境

- 代码版本:
  Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
这段代码比较可疑，但是未看到系统崩溃。

![image](https://user-images.githubusercontent.com/3538629/70887331-9c314500-2018-11ea-8520-427256580a14.png)

get agent reports是一个常用函数，查询坐席状态，会同步给浏览器端。

还是需要给出崩溃的root cause，并且这个描述和我们的了解不符，没有出现经常崩溃的现象。

1）系统配置需要 8GB内存及以上，最少8GB
2）CPU颗数2个或以上。
