### ISSUE TITLE
[cc]当前在线用户所用浏览器不能正确识别 

### ISSUE THREAD

**Issue by wq11123** [chatopera/cosin#25]
# 描述
用不同浏览器与客服聊天，却都显示chrome
## 现在行为
如下图，一个是QQ浏览器 一个是谷歌浏览器

![](https://user-images.githubusercontent.com/40993206/44763062-069c4880-ab7c-11e8-86f5-6880e6468ce4.png)

## 预期行为

# 解决方案

# 环境

* 代码版本:
The commit hash (`git rev-parse HEAD`)

**Comment by xianliwang** [comment]
@Samurais 企业版没有这个问题
