### ISSUE TITLE
install总是compose4j不成功

### ISSUE THREAD

**Issue by 15716597991** [chatopera/cosin#250]
![image](https://user-images.githubusercontent.com/53402282/71307554-418a5580-242b-11ea-988f-081da5fee185.png)
![image](https://user-images.githubusercontent.com/53402282/71307576-4cdd8100-242b-11ea-97dd-f22b1101d851.png)
仓库中也能找到这个依赖，但就是install不成功
![image](https://user-images.githubusercontent.com/53402282/71307604-74cce480-242b-11ea-9c6f-30aea966cbf9.png)
jdk也是对的，maven也没问题。求解

**Comment by Samurais** [comment]
在命令行，进入 contact-center/app 目录，然后执行：mvn idea:idea。
这时候会生成IDEA的项目描述文件，然后从IDEA点击"导入项目" ，在检查Maven Profile时，选择 chatopera.
详细参考：[春松客服开发文档](https://github.com/chatopera/cosin/wiki/%E6%98%A5%E6%9D%BE%E5%AE%A2%E6%9C%8D%EF%BC%9A%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83)

**Comment by 15716597991** [comment]
没有

**Comment by 15716597991** [comment]
感觉说的没啥用。完全没效果

**Comment by 15716597991** [comment]
![image](https://user-images.githubusercontent.com/53402282/71319844-8de29d80-24de-11ea-8aed-bf6bcd756bc9.png)
说的是选择这个吧

**Comment by Samurais** [comment]
导入项目的时候，选择maven

![image](https://user-images.githubusercontent.com/3538629/71319912-5e806080-24df-11ea-821b-33d8deae9b9c.png)


下一步，选择maven projects

![image](https://user-images.githubusercontent.com/3538629/71319921-6cce7c80-24df-11ea-8a86-a9a18679a274.png)

**Comment by 15716597991** [comment]
![image](https://user-images.githubusercontent.com/53402282/71321007-84613180-24ee-11ea-9fd8-59c30f736542.png)
dia点击完maven时这个画面，完全不一样吧。还有就是其他我从github上拉下来的项目都没有问题。奇怪了，导入项目至少我还是会的吧
