### ISSUE TITLE
服务器配置https报错，本地启动没问题

### ISSUE THREAD

**Issue by peck001** [chatopera/cosin#254]
# 描述
服务器配置https报错，本地启动没问题
下面是报错信息
failed: WebSocket is closed before the connection is established
failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

浏览器请求头出现这个
![image](https://user-images.githubusercontent.com/44854938/71431578-b4d2e680-270d-11ea-8d78-b98f1eff4dc4.png)

下面是nginx配置
![image](https://user-images.githubusercontent.com/44854938/71431610-ffecf980-270d-11ea-8eef-0a146b57c7ac.png)

**Comment by Samurais** [comment]
@peck001 HTTPS的问题解决了吗？

**Comment by peck001** [comment]
解决了，是因为nginx配置的是域名转发，然后html里面的socket是有端口的，导致出现问题，去掉端口就好了，
