### ISSUE TITLE
黑名单拉黑不进数据库

### ISSUE THREAD

**Issue by peck001** [chatopera/cosin#257]
# 描述
![image](https://user-images.githubusercontent.com/44854938/71541655-6b95c780-2997-11ea-8389-7a8fecfb9b5f.png)

![image](https://user-images.githubusercontent.com/44854938/71541665-8ec07700-2997-11ea-9265-fbb47bc17cfe.png)

![image](https://user-images.githubusercontent.com/44854938/71541699-fc6ca300-2997-11ea-88cc-ffaa7dd65c46.png)

本地是最新的git上的代码，演示区是正常的。拉黑能够进入黑名单列表，但是，本地进不去，也没报错，打断点，调试，没发现问题，就是存入不进数据库

## 预期行为

# 解决方案

# 环境

- 代码版本:
  Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
如果你打断点了，那么拉黑时，执行到该断点了吗？就是保存到数据库的地方。
如果没有保存成功，应该会报错。

**Comment by peck001** [comment]
这个是先加入了黑名单表，然后redis也有显示，但是
![image](https://user-images.githubusercontent.com/44854938/71567069-62237100-2af7-11ea-9fd8-8cc88b984d13.png)
走到这个代码之后，黑名单表数据就被删除了，redis数据也被删除了，不是在一个小时之后删除的

**Comment by Samurais** [comment]
拉黑时间是设置为1小时？
ActiveMQ是用我们的docker-compose.yml里的吗？

这个功能依赖于ActiveMQ的一个Schedule的功能，添加环境变量：

https://github.com/chatopera/cosin/blob/osc/docker-compose.yml#L66

**Comment by peck001** [comment]
我这个没用docker，直接用的application.properties 这个文件里面的

**Comment by Samurais** [comment]
@peck001 
参考上面评论，设置 环境变量 “ ACTIVEMQ_ENABLED_SCHEDULER” 在ActiveMQ服务上。

**Comment by peck001** [comment]
![image](https://user-images.githubusercontent.com/44854938/71567252-8895dc00-2af8-11ea-90c9-13a5def35e18.png)
这个加了

**Comment by Samurais** [comment]
在ActiveMQ中设置ACTIVEMQ_ENABLED_SCHEDULER，不是你发的那个变量。

**Comment by peck001** [comment]
好的，谢谢
