### ISSUE TITLE
[cc] 无法查看访客轨迹

### ISSUE THREAD

**Issue by wq11123** [chatopera/cosin#26]
# 描述
当有访客在线时，客服可以通过点击首页“当前在线用户列表”右侧轨迹按钮查看访客轨迹，或者通过会话历史中“当前会话”查看访客轨迹
## 预期行为

# 解决方案

# 环境

* 代码版本:
The commit hash (`git rev-parse HEAD`)

**Comment by xianliwang** [comment]
@Samurais 企业版没有这个问题

**Comment by Samurais** [comment]
5.0.0版本解决此问题。
