### ISSUE TITLE
编译不成功，环境都部署搭建好了

### ISSUE THREAD

**Issue by Zct-123** [chatopera/cosin#260]
# 描述

提交[公司信息说明](http://chatopera.mikecrm.com/lVtMuGN)后优先处理解决！

## 功能
![QQ图片20200101210215](https://user-images.githubusercontent.com/57829156/71641847-2fd36880-2cdd-11ea-8443-4b3cd6459377.png)
![QQ图片20200101210215](https://user-images.githubusercontent.com/57829156/71641848-3235c280-2cdd-11ea-80cb-212d022b5181.png)

## 非产品缺陷请联系商务获得支持

https://www.chatopera.com/mail.html

```
* 定制化开发
* 插件
* 培训
……
```

# 环境

- 代码版本:
  Git commit hash (`git rev-parse HEAD`)

**Comment by Zct-123** [comment]
[Desktop.zip](https://github.com/chatopera/cosin/files/4014096/Desktop.zip)

**Comment by Samurais** [comment]
如果是在IDEA中编译，需要在IDEA中设置JDK。而不是在操作系统中设置。
 
![image](https://user-images.githubusercontent.com/3538629/71641874-80e35c80-2cdd-11ea-8a96-048befcd8d9d.png)

**Comment by Zct-123** [comment]
好的，谢谢，这问题已解决
