### ISSUE TITLE
访客端浏览器打开适配问题，屏幕装不全，有个白条。

### ISSUE THREAD

**Issue by bestmarx** [chatopera/cosin#261]
[#]([url](url)) 描述

## safari和chrome苹果手机打开客服访客端，屏幕不全屏
##如果官方不想解决这个适配问题，可以提供下这个文件得修改路径码?我们尝试修改适配下，试试！

![image](https://user-images.githubusercontent.com/49609561/71655178-ae2d1a80-2d70-11ea-9a2c-511b14437a88.png)
![image](https://user-images.githubusercontent.com/49609561/71655217-d61c7e00-2d70-11ea-8139-052501299091.png)

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
请问是 iPhone 几？

**Comment by bestmarx** [comment]
iphone 8，和7p，还有华为，oppo都是这样，

**Comment by mukaiu** [comment]
body style 问题，近期修复
