### ISSUE TITLE
单服务部署 docker-compose启动contact-center服务报错500

### ISSUE THREAD

**Issue by 8823Senior** [chatopera/cosin#264]
#### 环境 
Centos7.5
#### 操作步骤
git clone https://github.com/chatopera/cosin.git
cd cosin
docker-compose up -d mysql
docker-compose up -d redis
docker-compose up -d elasticsearch
docker-compose up -d activemq
以上四个服务启动正常
docker-compose up -d contact-center 报错
Pulling contact-center (chatopera/contact-center:develop)...
Trying to pull repository docker.io/chatopera/contact-center ... 
develop: Pulling from docker.io/chatopera/contact-center
6abc03819f3e: Downloading [=>                                                 ] 579.1 kB/28.86 MB
05731e63f211: Download complete
0bd67c50d6be: Download complete
77d7067df2d3: Waiting
69d84ef50804: Waiting
a17bbdb9754f: Waiting
6d7e916dbd6b: Waiting
d2d03a58c38e: Waiting
f3e6c9c30e79: Waiting
b3f06d3f3e16: Waiting
87dc5fd26804: Waiting
974daa2cdfb1: Waiting
b0c843952ca0: Waiting
6cad1efc89c7: Waiting
ERROR: error pulling image configuration: received unexpected HTTP status: 500 Internal Server Error

**Comment by Samurais** [comment]
该情况是网络原因导致，解决方案如下：

1. 找一个网络条件好的电脑或服务器，安装docker

2. 在新的电脑下载镜像

方法，执行命令：
```
docker pull IMAGE_NAME
```

IMAGE_NAME 参考 docker-compose.yml 中各服务的image，
比如：
`docker pull chatopera/contact-center:develop`

春松客服包含多个image。

3. 下载好image后，导出image
将所有image使用下面命令导出为 tgz 文件
```
docker save chatopera/contact-center:develop > cc.docker.tgz
```

4. 将所有导出的image tgz文件上传到目标部署的服务器
即网络条件不好的机器，比如用 FTP工具或SCP命令。

5. 上传到目标机器后，安装镜像
`docker load < cc.docker.tgz`

安装成功后，会提示。

6. 启动春松客服

```
cd cosin # 源文件下载地址
docker-compose up -d contact-center
```

以上。

**Comment by 8823Senior** [comment]
docker pull charopera/contact-center:develop
Trying to pull repository docker.io/charopera/contact-center ... 
repository docker.io/charopera/contact-center not found: does not exist or no pull access
这是找不到或没权限😭

**Comment by Samurais** [comment]
写错了，你按照docker-compose.yml里的image下载。
```
docker pull charopera/contact-center:develop --> docker pull chatopera/contact-center:develop
```

**Comment by 8823Senior** [comment]
按照yml还是500，网络已经换了很快

docker pull chatopera/contact-center:develop

Trying to pull repository docker.io/chatopera/contact-center ... 
develop: Pulling from docker.io/chatopera/contact-center
6abc03819f3e: Downloading [===========>                                       ] 6.375 MB/28.86 MB
05731e63f211: Download complete 
0bd67c50d6be: Download complete 
77d7067df2d3: Waiting 
69d84ef50804: Waiting 
a17bbdb9754f: Waiting 
6d7e916dbd6b: Waiting 
d2d03a58c38e: Waiting 
f3e6c9c30e79: Waiting 
b3f06d3f3e16: Waiting 
87dc5fd26804: Waiting 
974daa2cdfb1: Waiting 
b0c843952ca0: Waiting 
6cad1efc89c7: Waiting 
error pulling image configuration: received unexpected HTTP status: 500 Internal Server Error

**Comment by Samurais** [comment]
根据报错你在网络上搜索问题的原因和解决方案吧，可能是还要换一个电脑，或者等一会再试。

**Comment by 8823Senior** [comment]
换成 阿里云机器顺利下载，虽然有点慢（没有使用容器镜像加速）
docker pull chatopera/contact-center:develop
已经顺利启动，其他人有此问题，可参考
