### ISSUE TITLE
请问，能不能提供一下idea配置运行环境变量时的完整截图，目前文档的截图没有截全

### ISSUE THREAD

**Issue by wzl789139** [chatopera/cosin#267]

**Comment by Samurais** [comment]
参考文件：https://github.com/chatopera/cosin/blob/osc/contact-center/app/src/main/resources/application.properties

该文件中键名的小写改为大写，"-"和"."改为小写，就得到了环境变量名字。

https://github.com/chatopera/cosin/blob/d77b86bfc9e63c7c035b0fd0188429dd800c206e/contact-center/app/src/main/resources/application.properties#L18,L30


比如，application.node.id 转换成环境变量就是 "APPLICATION_NODE_ID"，application.properties 中的值是默认值，通过环境变量可覆盖。
