### ISSUE TITLE
多个网站接入客服，若要不同坐席处理不同网站的客服联系是否只能部署多台？

### ISSUE THREAD

**Issue by 8823Senior** [chatopera/cosin#269]
如果部署单服务，但是接入多个网站，那么是 所有就绪客服 处理这多个网站的 联系在线客服 请求吗？

能否做到：用户从不同网站点击联系客服，根据不同网站来 分配到指定的客服，而不是所有客服

还是说，如果要实现 不同的客服 处理 不同网站的联系客服请求，只能部署多个服务，各自配置接入网站？

**Comment by Samurais** [comment]
创建不同技能组，在网站渠道设计中，设置客服信息，绑定单一技能组即可。
![image](https://user-images.githubusercontent.com/3538629/71767127-d456e400-2f43-11ea-906f-8ccb52d9ee4e.png)
