### ISSUE TITLE
[cc]快捷回复导出的Excel是空白 

### ISSUE THREAD

**Issue by wq11123** [chatopera/cosin#27]
# 描述
快捷回复导出的Excel是空白，并且命名错误，全部联系人和全部客户导出都有此问题，详见#739
## 现在行为

![](https://user-images.githubusercontent.com/40993206/44699291-1c473a80-aab6-11e8-90d9-733b2030e907.png)

## 预期行为

# 解决方案

# 环境

* 代码版本:
The commit hash (`git rev-parse HEAD`)

**Comment by xianliwang** [comment]
快捷回复更新为知识库快捷
