### ISSUE TITLE
项目导入idea，没有生成springboot启动项，去配置也没有找到springboot

### ISSUE THREAD

**Issue by Zct-123** [chatopera/cosin#270]
![0B60F371-69E8-4BAF-BB46-51C4191B4AE9](https://user-images.githubusercontent.com/57829156/71767786-edaf5e80-2f4a-11ea-83db-2be3f0526738.png)
# 描述

提交[公司信息说明](http://chatopera.mikecrm.com/lVtMuGN)后优先处理解决！

## 非产品缺陷请联系商务获得支持

https://www.chatopera.com/mail.html

```
* 定制化开发
* 插件
* 培训
……
```

# 环境

- 代码版本:
  Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
使用 IDEA Prof. 
IDEA Community 版本没有Spring开发工具。
