### ISSUE TITLE
只需基础模块中的客服相关功能，需要费用吗？是否需要贵公司授权？

### ISSUE THREAD

**Issue by 8823Senior** [chatopera/cosin#272]
想接入我们自己的商业化系统中，想咨询下相关授权，费用。
目前需求：
只需基础模块中的客服相关功能，
如果自己私有部署，是否需要贵公司授权？
如果上青云的话应该就是已经授权的，购买服务即可使用吧？

**Comment by Samurais** [comment]
> 只需基础模块中的客服相关功能

该部分代码在 https://github.com/chatopera/cosin，我们已经授权为Apache2.0协议。

> 如果自己私有部署，是否需要贵公司授权？

 https://github.com/chatopera/cosin 下的代码已经获得授权了。

> 如果上青云的话应该就是已经授权的，购买服务即可使用吧？

青云的服务是按时计费的，不过现在因为版本冲突，还没有升级到最新版，我们不建议使用。青云的AppCenter内服务春节后升级。
