### ISSUE TITLE
页面显示问题，就是客服的聊天页面以及客户的聊天页面都会出现显示不完整

### ISSUE THREAD

**Issue by peck001** [chatopera/cosin#273]
# 描述
 enhancement
![image](https://user-images.githubusercontent.com/44854938/71805390-134e7c00-30a1-11ea-926e-f230dfd34391.png)
上面是客户在发完图片之后出现的，图片展示不完整，H5端也是
![image](https://user-images.githubusercontent.com/44854938/71805452-3ed16680-30a1-11ea-8072-8b2260736c9b.png)
上面是客服的聊天页面，也是一样的情况

## 预期行为

# 解决方案

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
@xianliwang 帮忙验证一下这个问题，什么情况下图片会显示不完整。

**Comment by xianliwang** [comment]
点击查看图片是完整的，上传图片后滚动条没有置底在窗口需要下拉一下滚动条

![image](https://user-images.githubusercontent.com/52594347/71814377-29ffcd80-30b7-11ea-89de-3ddb96e4cb68.png)
![image](https://user-images.githubusercontent.com/52594347/71814520-a2ff2500-30b7-11ea-94d9-540e222f9073.png)
