### ISSUE TITLE
不同技能组的客服可相互看到与客户的聊天记录？

### ISSUE THREAD

**Issue by 8823Senior** [chatopera/cosin#274]
### 测试准备
1. 组织机构-创建了2个部门（这应该就是技能组了），并创建2个坐席，每个部门各自添加了1个客服
2. 客服接入-网站列表，分别创建2个接入网站A和B，且 都启用技能组模式，各自绑定单一技能组

##### 同一个客户
先是联系了网站A 的客服并聊天（留下一些沟通记录）
再联系另一个网站B 的客服，
此时，网站B的 客服坐席，可以看到 该客户与 网站A的客服的聊天记录，
且如果客户再次联系网站A的客服坐席， 网站A的客服坐席，也能看到 该客户与网站B客服的 聊天记录

### 问题
这个是本来就是这样设计的吗？还是BUG？

**Comment by Samurais** [comment]
目前设计如此，下一个版本 v6.0.0中会进行权限的优化。

**Comment by 8823Senior** [comment]
v6.0.0 有计划发布日期吗

**Comment by Samurais** [comment]
明年2月份
