### ISSUE TITLE
集成机器人报错

### ISSUE THREAD

**Issue by captain36** [chatopera/cosin#275]
# 描述
集成机器人时报
![图片](https://user-images.githubusercontent.com/7778643/71812075-3e40cc00-30b1-11ea-98a2-d964b9f21363.png)
后台日志显示：
![图片](https://user-images.githubusercontent.com/7778643/71812102-4ef14200-30b1-11ea-91a8-2ee57df8a1c0.png)
jdk版本：
![图片](https://user-images.githubusercontent.com/7778643/71812127-59abd700-30b1-11ea-872b-6006a9036de3.png)
Windows本地可以，远程Linux不行

## 预期行为

# 解决方案

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [x] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
所以，CentOS内也用的是Amazon JDK?
https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html

**Comment by captain36** [comment]
> Windows、centos用的都是oracle的jdk1.8
> 
> 所以，CentOS内也用的是Amazon JDK?
> https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html

**Comment by captain36** [comment]
centos是运行项目打包的jar的，没有通过docker，Windows是idea运行

**Comment by captain36** [comment]
已解决，参考方法：https://www.oschina.net/question/12_19249
