### ISSUE TITLE
win10 环境构建docker镜像失败

### ISSUE THREAD

**Issue by Paul890** [chatopera/cosin#276]
# 描述
win10 环境构建docker镜像失败
## 现在行为
输入命令：
docker build --build-arg VCS_REF=$519992c\
docker build --build-arg APPLICATION_BUILD_STR='20200107'\
 --build-arg APPLICATION_CUSTOMER_ENTITY=OSC\
 --no-cahce\
 --force-rm=true tag chatopera/contact-center:$519992c .

## 预期行为
构建镜像成功

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
我们不提供面向Windows打包的Docker镜像脚本。
