### ISSUE TITLE
idea maven打war包失败，git插件报错

### ISSUE THREAD

**Issue by 8823Senior** [chatopera/cosin#277]
maven clean->install
git插件报错
Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.5:revision (default) on project contact-center: .git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml 
能删除本地删除这个plugin打包可以成功，这个是否必要呢？

**Comment by Samurais** [comment]
使用 git clone 下载源码来解决这个问题。
构建路径必须在git库内。
