### ISSUE TITLE
打war包成功，部署到tomcat失败git.build.version找不到

### ISSUE THREAD

**Issue by 8823Senior** [chatopera/cosin#278]
windows开发环境
git clone 之后，进入 cosin\contact-center\app 打包
mvn clean install -Dmaven.test.skip=true  打war包成功

但是部署到 tomcat 却报错了
ERROR o.s.boot.SpringApplication - Application startup failed [localhost-startStop-1] 
org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'applicationController': 
Injection of autowired dependencies failed; 
nested exception is java.lang.IllegalArgumentException: 
Could not resolve placeholder 'git.build.version' in value "${git.build.version}"

解压软件打开war包，可以看到 contact-center.war\WEB-INF\classes 目录下有 git.properties，且也有 git.build.* 多个属性
为什么还是失败呢？

那么该属性应该如何配置呢？

**Comment by Samurais** [comment]
使用Git下载代码，然后进行编译。

**Comment by wangweitest** [comment]
使用git下载源码后还是存在这个问题
