### ISSUE TITLE
访客端集成移动上兼容问题

### ISSUE THREAD

**Issue by hzg-java** [chatopera/cosin#284]
对话窗口上下滑动的时候输入框和对话北京出现层级滚动

**Comment by hzg-java** [comment]
![{IKU{3KY Q6}T8{CUWJT2BC](https://user-images.githubusercontent.com/57212161/72135961-a4d02d80-33c2-11ea-9921-1dc6d440e618.jpg)

**Comment by xianliwang** [comment]
已修复
![image](https://user-images.githubusercontent.com/52594347/72588767-4829c100-3934-11ea-8e64-40bf21cc87c0.png)
