### ISSUE TITLE
mq连接失败，求大佬帮忙看一下

### ISSUE THREAD

**Issue by Zct-123** [chatopera/cosin#292]
mq配置文件
![DD618206-11C9-46F7-AE78-45B302D27F58](https://user-images.githubusercontent.com/57829156/72435024-126fc580-37d8-11ea-97f1-d4e7d42e21bf.png)
测试安装成功服务器
![DC44E18F-9E4D-4D2A-8463-24B8DDDB827A](https://user-images.githubusercontent.com/57829156/72435059-21567800-37d8-11ea-84cb-f2b45fae824c.png)

项目运行报错
ERROR o.s.j.l.DefaultMessageListenerContainer - Could not refresh JMS Connection for destination 'cskefu.agent.audit' - retrying using FixedBackOff{interval=5000, currentAttempts=43, maxAttempts=unlimited}. Cause: Cannot send, channel has already failed: tcp://47.111.226.125:8162 [DefaultMessageListenerContainer-1] 
连接失败，

项目运行web端，资源映射缺失

**Comment by Samurais** [comment]
使用我们推荐的方式运行ActiveMQ

```
git clone https://github.com/chatopera/cosin.git
cd cosin
docker-compose up -d activemq
```

**Comment by Samurais** [comment]
在ActiveMQ上有一些配置，用我们的方式 Just work.

**Comment by Samurais** [comment]
遇到问题使用Issue查询功能，先找找相关的。

```
https://github.com/chatopera/cosin/issues?utf8=%E2%9C%93&q=activemq
```
![image](https://user-images.githubusercontent.com/3538629/72770167-02247400-3c38-11ea-9e45-1d095a812a8c.png)
