### ISSUE TITLE
文字加表情出现严重bug,导致模板解析失败

### ISSUE THREAD

**Issue by ChinaCowB** [chatopera/cosin#297]
# 描述
文字加表情出现严重bug,导致模板解析失败

## 现在行为

![image](https://user-images.githubusercontent.com/48076911/74312718-2560c000-4dad-11ea-822c-09122b87a9c0.png)

## 预期行为

# 解决方案

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by kylezhang** [comment]
从截图中看不错问题，能否给出可以复现的步骤和数据。

**Comment by ChinaCowB** [comment]
> 从截图中看不错问题，能否获得可以复现的步骤和数据。

将文字输入最大字数限制设置成100,反正随便设置一个值,在访客端发送表情和字母一起,就会导致这个解析出现问题

**Comment by mukaiu** [comment]
此问题重构后修复
