### ISSUE TITLE
[cc]移动端用户进入在线对话，发送表情无法显示

### ISSUE THREAD

**Issue by wq11123** [chatopera/cosin#30]
# 描述
[cc]移动端用户通过浏览器进入在线对话，发送表情无法显示
## 现在行为

![](https://user-images.githubusercontent.com/40993206/44582810-5a520f00-a7d5-11e8-96ec-189ae5818deb.png)

## 预期行为

# 解决方案

# 环境
安卓手机
* 代码版本:
The commit hash (`git rev-parse HEAD`)

**Comment by mukaiu** [comment]
系统设置问题
