### ISSUE TITLE
访客端对话框编辑器截图功能无效

### ISSUE THREAD

**Issue by HHHutian** [chatopera/cosin#303]
# 描述
编辑器截图功能无效，使用了谷歌火狐等，不是兼容性问题

## 预期行为

# 解决方案

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ √] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
该功能为已知问题，该截图方案将来会去掉，因为在浏览器内JS实现截图有很多限制。
