### ISSUE TITLE
客服关闭浏览器或断网后，没有自动离线

### ISSUE THREAD

**Issue by wmm7172** [chatopera/cosin#304]
# 描述

## 现在行为
客服关闭浏览器或者断网后,很小概率依然处于在线状态，且访客能分配到该客服

## 预期行为
客服关闭浏览器或者断网一定时间后自动离线，访客不会分配到该客服。

# 解决方案

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
坐席端，断开后10s内才离线
