### ISSUE TITLE
无法创建机器人

### ISSUE THREAD

**Issue by LanceLee502** [chatopera/cosin#305]
# 描述
![image](https://user-images.githubusercontent.com/19965857/76179437-dcf2c180-61f5-11ea-9341-321e94cc27c6.png)

## 功能

创建机器人：
1、服务器可ping同外网；
2、机器人从未创建；
3、clientId正确

# 环境
centos7+docker
## 操作系统
Linux(CentOS)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by LanceLee502** [comment]
My error in operation has been solved now

**Comment by LanceLee502** [comment]
本地后台请求：/api/V1/Chatbot/{Client Id}，这个接口的时候，报非法的timeStamp（{"rc":1,"error":"invalid timestamp."}）,本地时区：北京

**Comment by Samurais** [comment]
操作系统需要设置的时间同步为互联网时间，参考
https://www.sysgeek.cn/manage-time-server-windows-10/

也可以设置为阿里云时间同步器
https://blog.csdn.net/qq_35448976/article/details/78977164

**Comment by haitoo** [comment]
我遇到的问题返回以下错误，根据错误提示实在查不出来原因。最后在群里问，发现也是时间未同步的问题，开启同步时间后解决。
{"rc":5,"error":"Chatopera云服务：无法访问该机器人，请确认【1】该服务器可以访问互联网，【2】该聊天机器人已经创建，【3】clientId和Secret正确设置。"}

**Comment by Samurais** [comment]
机器人接入文档参考：
https://github.com/chatopera/cosin/wiki/%E6%9C%BA%E5%99%A8%E4%BA%BA%E5%AE%A2%E6%9C%8D
