### ISSUE TITLE
前后端分离方案

### ISSUE THREAD

**Issue by cuijiaxu** [chatopera/cosin#308]
## 功能

请问有没有单独对接socket.io的接口文档？目前有意做单独的前端展示。

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
关于使用socketio实现即时通话的设计，需要参考[春松客服大讲堂](https://github.com/chatopera/cosin/wiki/%E6%98%A5%E6%9D%BE%E5%AE%A2%E6%9C%8D%E5%A4%A7%E8%AE%B2%E5%A0%82)内的相关内容，有详细介绍，看完视频讲解后您能放心修改代码。

**Comment by Samurais** [comment]
目前没有计划用前后端分离方式实现。
