### ISSUE TITLE
机器人创建失败

### ISSUE THREAD

**Issue by HHHutian** [chatopera/cosin#309]
![_~~JE7 (O ML75E)FC6O}HT](https://user-images.githubusercontent.com/44494489/77298993-bf117a80-6d26-11ea-85d1-232d4b562af8.png)
#305 后台报错信息
com.chatopera.bot.exception.ChatbotException: com.chatopera.bot.exception.ChatbotException: com.mashape.unirest.http.exceptions.UnirestException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by kylezhang** [comment]
参考issue #305
