### ISSUE TITLE
部署服务器频繁断线

### ISSUE THREAD

**Issue by Assassin-YingZhou** [chatopera/cosin#312]
连接初始化成功
http://services。utvgpk. com: 8035/admin/im/index. html
ping:1586327327747
ping:1586327387747
连接已断开

**Comment by Samurais** [comment]
是否是服务器因为什么原因不断被重启了？

**Comment by Samurais** [comment]
机器配置怎么样？内存是多少？是用我们部署文档介绍的方式部署的吗？
https://github.com/chatopera/cosin/wiki/%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%83%A8%E7%BD%B2

**Comment by Assassin-YingZhou** [comment]
已经处理好了 机器是4和8g的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Samurais"<notifications@github.com&gt;; 
发送时间: 2020年4月8日(星期三) 下午5:15
收件人: "chatopera/cosin"<cosin@noreply.github.com&gt;; 
抄送: "周影"<1317216521@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [chatopera/cosin] 部署服务器频繁断线 (#312)





 
机器配置怎么样？内存是多少？是用我们部署文档介绍的方式部署的吗？
 https://github.com/chatopera/cosin/wiki/%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%83%A8%E7%BD%B2
