### ISSUE TITLE
点击客服坐席SQL报错

### ISSUE THREAD

**Issue by xgdz** [chatopera/cosin#313]
点击客服坐席模块，报sql错误
There was an unexpected error (type=Internal Server Error, status=500).
Mondrian Error:Internal error: Error while executing query [select {[Measures].[????], [Measures].[?????????], [Measures].[?????????]} ON COLUMNS, NonEmptyCrossJoin([time].[??].Members, NonEmptyCrossJoin([skill].[???].Members, [agent].[??].Members)) ON ROWS from [??] ]

**Comment by Samurais** [comment]
服务是怎么部署的？

参考文档，
https://github.com/chatopera/cosin/wiki

**Comment by xgdz** [comment]
这和部署没关系吧，因为后台报错是sql语法的问题，而且我截取了sql运行，确实这条sql语句有问题
SQL:
select
	date_format(agentservice.createtime, '%Y-%m-%d') as `c0`,
	`uk_organ`.`name` as `c1`,
	`cs_user`.`uname` as `c2`
from
	(
	select
		*
	from
		uk_agentservice
	where
		1 = 1
		AND orgi = 'cskefu') as `agentservice`,
	`uk_organ` as `uk_organ`,
	`cs_user` as `cs_user`
where
	`agentservice`.`agentskill` = `uk_organ`.`id`
	and `agentservice`.`agentno` = `cs_user`.`id`
group by
	date_format(agentservice.createtime, '%Y-%m-%d'),
	`uk_organ`.`name`,
	`cs_user`.`uname`
order by
	ISNULL(date_format(agentservice.createtime, '%Y-%m-%d')) ASC,
	date_format(agentservice.createtime, '%Y-%m-%d') ASC,
	ISNULL(`uk_organ`.`name`) ASC,
	`uk_organ`.`name` ASC,
	ISNULL(`cs_user`.`uname`) ASC,
	`cs_user`.`uname` ASC

**Comment by Samurais** [comment]
有关系，按照我们文档来，Just work.
