### ISSUE TITLE
是否考虑升级 Spring boot 版本到 2.x ?

### ISSUE THREAD

**Issue by XieEDeHeiShou** [chatopera/cosin#317]
# 描述

0. 是否有计划迁移到 Spring boot 2.x 版本?
0. 是否接受迁移到 Spring boot 2.x 版本的 PR?

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [x] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash :d72b5709 on 2020/4/2 at 18:24

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
升级需要重写代码比较多，今年无法保证。
您有什么需求一定要用spring boot 2.x 吗？

**Comment by XieEDeHeiShou** [comment]
没有什么特定的需求一定要用 2.x 版, 但是

_"Beacuse it's there!"_

**Comment by Samurais** [comment]
明年吧，今年太难了 😸
