### ISSUE TITLE
https部署后访问 没有反应

### ISSUE THREAD

**Issue by Zct-123** [chatopera/cosin#318]
下载好的阿里云证书
![Pasted Graphic](https://user-images.githubusercontent.com/57829156/79135548-1795de00-7de2-11ea-8614-f13b45b93c67.png)
部署
![Pasted Graphic 1](https://user-images.githubusercontent.com/57829156/79135639-42803200-7de2-11ea-8f47-8aaa842a0b8a.png)

![Pasted Graphic 2](https://user-images.githubusercontent.com/57829156/79135623-3ac08d80-7de2-11ea-9a31-bcfaf1f5caf8.png)
![Pasted Graphic 3](https://user-images.githubusercontent.com/57829156/79135657-490ea980-7de2-11ea-9665-f24124f664b6.png)

**Comment by Zct-123** [comment]
现在可以访问，但是我想把8035端口去掉，怎么弄

**Comment by Zct-123** [comment]
那个我知道怎么弄了，但是nginx没有在docker-compose ps中

**Comment by Samurais** [comment]
duplicated with #319
