### ISSUE TITLE
https私有部署，问题。nginx启动不起来，急急急急急急

### ISSUE THREAD

**Issue by Zct-123** [chatopera/cosin#319]
部署好项目后。docker-compose ps 没有看到nginx容器
![image](https://user-images.githubusercontent.com/57829156/79233897-07dad000-7e9c-11ea-923d-9360beb3e22d.png)
镜像中nginx是存在的
![image](https://user-images.githubusercontent.com/57829156/79234126-686a0d00-7e9c-11ea-9d9b-70fc9b88512d.png)
我按照文档中配置
下面是nginx配置
![image](https://user-images.githubusercontent.com/57829156/79234559-03fb7d80-7e9d-11ea-8245-9d7e59a21144.png)
配置好重启，可以域名访问
![image](https://user-images.githubusercontent.com/57829156/79234715-41600b00-7e9d-11ea-8c90-f9b46b6a1f9d.png)
但是他的证书没有生效，阿里云客服回应是nginx没有启动
这该怎么解决

**Comment by Samurais** [comment]
@mukaiu https://github.com/chatopera/cosin/wiki/%E7%A7%81%E6%9C%89%E9%83%A8%E7%BD%B2%E9%85%8D%E7%BD%AEHTTPS

文档写的不够细致，需要在配置后，docker-compose.yml 加入nginx container 并启动 docker-compose up -d nginx

你帮忙更新一下文档。

**Comment by Zct-123** [comment]
docker-compose.yml里面不是有nginx配置了吗

![image](https://user-images.githubusercontent.com/57829156/79330142-9bb7a500-7f4b-11ea-86b0-fc5f4874e064.png)

**Comment by Samurais** [comment]
```
docker-compose up -d contact-center
```

这个命令不会启动 nginx, 启动nginx用

```
docker-compose up -d nginx
```

查看服务使用启动用
```
docker-compose ps
```

**Comment by Zct-123** [comment]
![image](https://user-images.githubusercontent.com/57829156/79330417-1385cf80-7f4c-11ea-85bd-d2228b278c37.png)
启动了后nginx状态不对

**Comment by Samurais** [comment]
```
docker-compose logs -f nginx
```

查看日志，并把日志粘贴一下。只粘贴错误片段。
春松客服大讲堂上有docker和docker-compose内容，看一下！

**Comment by Zct-123** [comment]
OK，我看一下

**Comment by Zct-123** [comment]
这是日志
![image](https://user-images.githubusercontent.com/57829156/79330707-9444cb80-7f4c-11ea-881e-ec2d9fb45e6c.png)

**Comment by mukaiu** [comment]
确认一下证书文件名和配置文件里写的是否一致

**Comment by Zct-123** [comment]
证书是从阿里云下载下来，直接复制过去的，应该不是这问题

**Comment by Samurais** [comment]
你研究一下nginx模版里的每个配置项含义，尽信书不如无书。要有自己解决问题能力，我们不能一项一项帮你解答。现在已经发现问题了，请自行解决，感谢！

**Comment by Zct-123** [comment]
ok,我看一下nginx，感谢解答

**Comment by Zct-123** [comment]
这docker-compose.yml 中nginx的配置会出现立即停止重启问题
![image](https://user-images.githubusercontent.com/57829156/79337078-7335a800-7f57-11ea-9495-85a577c10938.png)

**Comment by mukaiu** [comment]
你那nginx停止的原因是，无法正确读取证书文件。可能的原因是文件名错误，SELinux 权限未配置等
