### ISSUE TITLE
[cc]搜索框多字段时，搜索按钮被遮挡 

### ISSUE THREAD

**Issue by wq11123** [chatopera/cosin#32]
# 描述
搜索框多字段时，搜索按钮被遮挡

## 现在行为

![](https://user-images.githubusercontent.com/40993206/44576442-2240d100-a7c1-11e8-8cb6-86ad3fa1b468.png)

## 预期行为
搜索按钮放在搜索框前面或者后面，不被遮挡
# 解决方案

# 环境

* 代码版本:
The commit hash (`git rev-parse HEAD`)

**Comment by xianliwang** [comment]
@Samurais 企业版没有这个问题

**Comment by xianliwang** [comment]
![image](https://user-images.githubusercontent.com/52594347/72599983-b7f87580-394d-11ea-98c5-9051020be0d5.png)
