### ISSUE TITLE
Windows系统由http改成https后，坐席无法分配

### ISSUE THREAD

**Issue by xgdz** [chatopera/cosin#321]
windows系统由http改成https后，人工坐席无法分配，导致发送不出消息
![K09OPUJ)RTMRDKOLCKQS5S3](https://user-images.githubusercontent.com/63387957/79847842-df4e5b00-83f2-11ea-9b03-240feca325cc.png)

项目相关配置如下

![HEBUW0JE8{IE6)`018O 0NS](https://user-images.githubusercontent.com/63387957/79848014-191f6180-83f3-11ea-89e1-82a749228461.png)

**Comment by kylezhang** [comment]
https部署，推荐看[私有部署配置HTTPS](https://github.com/chatopera/cosin/wiki/%E7%A7%81%E6%9C%89%E9%83%A8%E7%BD%B2%E9%85%8D%E7%BD%AEHTTPS)
