### ISSUE TITLE
按照部署文件docker 成功部署了，端口映射也开了，但是通过127.0.0.1:8035 访问不到

### ISSUE THREAD

**Issue by chen781414** [chatopera/cosin#326]
# 描述
 在WIN7 系统上使用VMWARE12 虚拟一台Centos 7系统，在 Centos 7 上按照单机部署文档部署docker  并且pull 到相关image 。docker-compress 正常运行容器，但通过 Centos 7上浏览器, 输入地址127.0.0.1:8035 无法访问服务。
![brower](https://user-images.githubusercontent.com/4187100/81467881-38e5c080-920e-11ea-8ef2-37d1aba2e966.png)

状态如下图：
![runstat](https://user-images.githubusercontent.com/4187100/81467678-f4a5f080-920c-11ea-9eac-0a8c88fea2e1.png)

![ps](https://user-images.githubusercontent.com/4187100/81467687-01c2df80-920d-11ea-83f3-f306725cc3ac.png)

网络有端口映射状态：
![netstat](https://user-images.githubusercontent.com/4187100/81467635-9e38b200-920c-11ea-933b-6a54239332ba.png)

服务日志DEBUG(无报错)
![LogInfo](https://user-images.githubusercontent.com/4187100/81467751-667e3a00-920d-11ea-9d50-45ad0b63153f.png)

# 环境
Win7-->VMWARE 12-->Centos7
Docker version 19.03.8, build afacb8b
docker-compose version 1.24.1, build 4667896b

## 操作系统
- [ ] Linux(CentOS 7)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by kylezhang** [comment]
在centos 上 `curl -i http://127.0.0.1:8035`看看？

**Comment by chen781414** [comment]
![testwet](https://user-images.githubusercontent.com/4187100/81633467-6b2a3480-943f-11ea-820b-a72699b03872.png)
感觉是网络映射没有实际生效

**Comment by Samurais** [comment]
有可能是iptables和docker network policy冲突，我们一直在用Ubuntu Server，可以先关闭防火墙测试。
