### ISSUE TITLE
修改模板上传服务器覆盖，没产生作用，这怎么解决

### ISSUE THREAD

**Issue by Zct-123** [chatopera/cosin#327]
修改模板上传服务器覆盖，没产生作用
1.我清除浏览器缓存
![Pasted Graphic 1](https://user-images.githubusercontent.com/57829156/81524266-13c68e80-9383-11ea-87cb-74407c2d1160.png)
2.设置了强制刷新
![Pasted Graphic](https://user-images.githubusercontent.com/57829156/81524278-25a83180-9383-11ea-881d-3b41746c9f22.png)
3.系统登出，重新登录后，也没有发生变化
4.本地部署产生的效果
![Pasted Graphic 2](https://user-images.githubusercontent.com/57829156/81524341-643dec00-9383-11ea-8bb1-8821969dc421.png)
上传服务器访问
![Pasted Graphic 3](https://user-images.githubusercontent.com/57829156/81524362-7586f880-9383-11ea-838b-fad5e5034757.png)
他还是访问到以前的资源
5.我清除了服务器缓存
![E1A96223-1E26-422A-9B1F-8AEAB4F7298E](https://user-images.githubusercontent.com/57829156/81524388-951e2100-9383-11ea-9385-fb1321c4ca27.png)
这问题怎么解决

**Comment by Zct-123** [comment]
本地改了模板样式，覆盖服务器文件。重启docker，没有产生效果

**Comment by kylezhang** [comment]
> 本地改了模板样式，覆盖服务器文件。重启docker，没有产生效果

1）模版样式具体是什么？
2）怎么上传怎么覆盖？
3）为什么不是用`版本控制软件`来做这些呢？

**Comment by Zct-123** [comment]
![image](https://user-images.githubusercontent.com/57829156/81525013-e5967e00-9385-11ea-8977-39815eb97ef0.png)
这是修改的模板

**Comment by mukaiu** [comment]
修改完 build 新的 docker image

**Comment by Zct-123** [comment]
这是之前的模板
![Pasted Graphic](https://user-images.githubusercontent.com/57829156/81525349-fb587300-9386-11ea-810d-4bb37ba2c11c.png)
我对他进行修改
![Pasted Graphic 1](https://user-images.githubusercontent.com/57829156/81525370-0f03d980-9387-11ea-8f8f-593e735001af.png)
我对他进行压缩上传到服务器zip格式
我找到这个模板的路径位置，把原来的删除掉，把上传 解压的放到删除的位置。
cp -r 上传文件 覆盖的位置
然后重启docker，在进行访问，还是访问到之前的效果

**Comment by kylezhang** [comment]
也就是你把`关于产品`删除掉了？

**Comment by Zct-123** [comment]
是把项目打成jar包与dockerfile一起来生成新的docker images
 @具体怎么操作****

**Comment by Zct-123** [comment]
![4DA1233A-ED7D-4C11-AE07-59AE195CF844](https://user-images.githubusercontent.com/57829156/81575885-21f3c980-93da-11ea-9dfa-eb55920800d3.png)
是这build 新的docker images 吗

**Comment by kylezhang** [comment]
> ![4DA1233A-ED7D-4C11-AE07-59AE195CF844](https://user-images.githubusercontent.com/57829156/81575885-21f3c980-93da-11ea-9dfa-eb55920800d3.png)
> 是这build 新的docker images 吗

你这个docker build 成功了吗，最后build了一个什么，看下镜像列表。

**Comment by Zct-123** [comment]
这dockerfile是自带的，还需要，修改什么吗？现在zh这样
![630CC6D0CD037FC673B5691387AFB8A2](https://user-images.githubusercontent.com/57829156/81579499-d42d9000-93de-11ea-9c92-f5402f9d3fa3.jpg)

**Comment by Zct-123** [comment]
![DC8784E5-9821-401A-B5FF-B71A9286AE6A](https://user-images.githubusercontent.com/57829156/81580014-764d7800-93df-11ea-89a3-4105170595fb.png)
docker build .
不应该是只需要build 新的contact_center镜像吗？这个是配置文件是不是有点多

**Comment by Zct-123** [comment]
![image](https://user-images.githubusercontent.com/57829156/81582608-d396f880-93e2-11ea-8049-91f2eaaf4da3.png)
成功之后是这样

**Comment by kylezhang** [comment]
```
docker build --build-arg VCS_REF=$PACKAGE_VERSION \
    --build-arg APPLICATION_BUILD_DATESTR=`date "+%Y%m%d.%H%M%S"` \
    --build-arg APPLICATION_CUSTOMER_ENTITY=OSC \
    --no-cache \
    --force-rm=true --tag chatopera/contact-center:$PACKAGE_VERSION .
```

**Comment by Zct-123** [comment]
![image](https://user-images.githubusercontent.com/57829156/81677429-86b72e80-9483-11ea-8914-af2a09c71630.png)
没有成功啊
