### ISSUE TITLE
请问客服系统支持IE浏览器吗？我在IE浏览器上点击在线客服后显示空白页，开发者模式有报错

### ISSUE THREAD

**Issue by buptls** [chatopera/cosin#328]
# 描述

## 功能

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
不支持IE浏览器
