### ISSUE TITLE
docker-compose nginx日志查看不了

### ISSUE THREAD

**Issue by Zct-123** [chatopera/cosin#335]
![image](https://user-images.githubusercontent.com/57829156/83110485-bb6aed00-a0f5-11ea-8999-96a5ec1d205d.png)
曾经重新启动服务可以查看，但过一会又不可用查看nginx日志
![image](https://user-images.githubusercontent.com/57829156/83110628-eead7c00-a0f5-11ea-8d11-6a02796e4b7f.png)
进入容器也是没有查看到日志，服务器防火墙关闭状态

**Comment by kylezhang** [comment]
可以看下 nginx docker 的docs.

**Comment by Samurais** [comment]
```
docker-compose logs -f nginx
```

f, follow.
