### ISSUE TITLE
百思不得其解，烦请老师解答下 socket.on("status",function(data){ ......}  方法对应后台的哪个类？

### ISSUE THREAD

**Issue by afcat-liuchao** [chatopera/cosin#336]
百思不得其解，烦请老师解答下cosin\contact-center\app\src\main\resources\templates\apps\im\index.html 这个文件的  socket.on("status",function(data){ ......}  方法对应后台的哪个类？

**Comment by kylezhang** [comment]
请阅读socketio文档。
