### ISSUE TITLE
https配置依然无效，请指导一下

### ISSUE THREAD

**Issue by Zct-123** [chatopera/cosin#338]
1.配置无效后，我进行检查nginx启动情况
![image](https://user-images.githubusercontent.com/57829156/83495293-10d63e00-a4ea-11ea-8584-d0a372a30f59.png)
2.nginx日志情况

![image](https://user-images.githubusercontent.com/57829156/83495540-69a5d680-a4ea-11ea-93a2-b1e7172d4dd8.png)

3.我的nginx配置文件
![image](https://user-images.githubusercontent.com/57829156/83495682-9ce86580-a4ea-11ea-8f1a-f734f5994854.png)
证书位置
![image](https://user-images.githubusercontent.com/57829156/83495761-b7bada00-a4ea-11ea-992e-1db94551d94d.png)
.env文件配置情况
![image](https://user-images.githubusercontent.com/57829156/83495962-f8b2ee80-a4ea-11ea-8121-e04997cefd8e.png)
服务器防火墙状态确定关闭

4.实行HTTPS访问
![image](https://user-images.githubusercontent.com/57829156/83496145-3e6fb700-a4eb-11ea-9a3c-598fa1dcebf6.png)
走8035端口可以访问成功
但是会报错，功能可用
![image](https://user-images.githubusercontent.com/57829156/83498161-1df52c00-a4ee-11ea-90e6-e8d9c2598db8.png)

**Comment by Zct-123** [comment]
可用访问了，但是还是报这个错误
![image](https://user-images.githubusercontent.com/57829156/83507177-c7421f00-a4fa-11ea-94ac-12ac9a04f42c.png)

**Comment by liuwei11** [comment]
解决了吗？我也是这个

**Comment by Zct-123** [comment]
浏览器报错吗？

**Comment by liuwei11** [comment]
是的。

**Comment by Zct-123** [comment]
好像是合并端口出现问题，他们HTTPS部署那里介绍合并端口，实现scket.io。但是我也没找到解决的办法，如果你解决了也麻烦给我分享一下，谢谢

**Comment by liuwei11** [comment]
好像是CC_SOCKET_PORT设置不起作用。一直请求的8036

**Comment by Zct-123** [comment]
CC_SOCKET_PORT这里不是改443端口吗

**Comment by liuwei11** [comment]
改了但是好像没生效。还是走的8036。

**Comment by Zct-123** [comment]
所以我觉得就是合并端口不成功，sample.env文件你改成.env，那些监听端口就没效果，项目就运行不起来。所以测试sample.env文件他是起效果的，就是不知道是哪里出现了问题

**Comment by kylezhang** [comment]
请仔细研究下`sample.env`与`.env`的作用。

**Comment by Zct-123** [comment]
sample.env他是监听docker-compose.yml文件的端口

**Comment by liuwei11** [comment]
docker-compose.yml   里的      # set a separated port for SSL
      - CS_IM_SERVER_SSL_PORT=${CC_SOCKET_PORT:-8036}没起作用。
直接改成 - CS_IM_SERVER_SSL_PORT=443就走443了

**Comment by Zct-123** [comment]
意思是两个文件一起改

**Comment by Zct-123** [comment]
![image](https://user-images.githubusercontent.com/57829156/83972925-9f492600-a915-11ea-887c-120ef3eb5bd1.png)
改了docker-compose.yml文件，重启项目，还是没有效果

**Comment by liuwei11** [comment]
用
docker-compose down
docker-compose up -d
重启。我的已经好了

**Comment by Zct-123** [comment]
感谢

**Comment by Samurais** [comment]
参考 博客，

https://chatopera.blog.csdn.net/article/details/105820829
