### ISSUE TITLE
大BUG,大BUG

### ISSUE THREAD

**Issue by romantictravel01** [chatopera/cosin#339]
1.客服掉线
   你关掉网络一分钟后,socket就进入了disconnect,此时打开网络客服就掉线了,页面还显示在线.无法重连,在disconnect方法里面用socket.open()也无效

2.第一个问题刷新页面,然后点击在线,客服重新上线,此时手机端就失去连接了,pc端好像是可以了

**Comment by kylezhang** [comment]
感谢反馈，如何有解决方案请直接提交PR，我们会merge。开源社区，人人可贡献代码。

**Comment by romantictravel01** [comment]
-----直接换系统了
