### ISSUE TITLE
技能组启动之后看不到技能组下的坐席

### ISSUE THREAD

**Issue by ChocolateTan** [chatopera/cosin#340]
技能组启动之后看不到技能组下的坐席，客服已经在线，并且设置了角色和组织架构
![image](https://user-images.githubusercontent.com/3889632/84100422-6eb0db80-aa3e-11ea-8985-957001ffa3bc.png)

**Comment by kylezhang** [comment]
请把上面说到的一些对象都截图，主要是看下这些对象之间的关联是否正确。

**Comment by ChocolateTan** [comment]
![image](https://user-images.githubusercontent.com/3889632/84218130-5e613500-ab00-11ea-8b4d-3013f6a5c4be.png)
![image](https://user-images.githubusercontent.com/3889632/84218144-68833380-ab00-11ea-8e65-e44e48718e52.png)

**Comment by ChocolateTan** [comment]
![image](https://user-images.githubusercontent.com/3889632/84218246-9ec0b300-ab00-11ea-98a0-2a5c381c5513.png)

**Comment by Samurais** [comment]
## 组织机构为技能组
![image](https://user-images.githubusercontent.com/3538629/91121516-8bb68b80-e6ca-11ea-9235-10ecaad4ebce.png)


## 设置角色
![image](https://user-images.githubusercontent.com/3538629/91121867-6a09d400-e6cb-11ea-8b47-a5620c3af655.png)


##  创建新用户

![image](https://user-images.githubusercontent.com/3538629/91121917-89a0fc80-e6cb-11ea-8962-509791ab8ae6.png)

关联到角色

![image](https://user-images.githubusercontent.com/3538629/91121957-9d4c6300-e6cb-11ea-97b8-c0d4cc22e412.png)


关联到组织机构

![image](https://user-images.githubusercontent.com/3538629/91121974-ab9a7f00-e6cb-11ea-9684-fa5dc02d365b.png)


## 创建网站渠道

![image](https://user-images.githubusercontent.com/3538629/91122000-b9e89b00-e6cb-11ea-898c-9ef1116af9d3.png)

渠道测试网址 https://cc.chatopera.com/testclient.html ，默认聊天控件

![image](https://user-images.githubusercontent.com/3538629/91122029-cf5dc500-e6cb-11ea-9c49-e1a80cc77592.png)

## 展示技能组列表

系统设置 -> 客服接入 -> 网站列表 -> localhost 接入 -> 客服信息

9、启用技能组模式： 开启

![image](https://user-images.githubusercontent.com/3538629/91122129-164bba80-e6cc-11ea-8af9-12a44f85b49a.png)

保存。

## 访客重新打开聊天页面

**相应客服列表中，只展示技能组里具有客服权限的，在线的，且是就绪空闲状态的人。**

### 没有客服在线

![image](https://user-images.githubusercontent.com/3538629/91122180-3ed3b480-e6cc-11ea-999d-cb755db0d856.png)


### 有客服上线
登入账号 shan

**Comment by Samurais** [comment]
使用docker image 以下版本解决。

```
chatopera/contact-center:25d67d6
```

默认最新的也可以。

```
chatopera/contact-center:develop
```

参考 [docker-compose.yml](https://github.com/chatopera/cosin/blob/osc/docker-compose.yml)
