### ISSUE TITLE
Windows搭建开发环境

### ISSUE THREAD

**Issue by ws364744954** [chatopera/cosin#341]
- [ ] Windows

## 代码版本

Windows搭建开发环境没有使用docker-compose部署，直接在windows  安装启动Elasticsearch 服务，ActiveMQ 服务MySQL 服务 Redis 服务，然后把项目导入到idea 里面，maven在下载jar包 有四个jar 找不到
![image](https://user-images.githubusercontent.com/34123063/84967612-f6859c80-b146-11ea-9a04-c456b1aeb93f.png)  
Cannot resolve com.chatopera.chatbot:sdk:2.1.0
Cannot resolve mondrian:mondrian:3.7.0
Cannot resolve it.sauronsoftware:jave:1.0.1
Cannot resolve com.chatopera.compose4j:compose4j:1.0.0

我想问我这种方式 能搭建开发环境不

**Comment by luqaing198855** [comment]
这是你maven仓库没有这4个包
你引入就好了

**Comment by luqaing198855** [comment]
这是你maven仓库没有这4个包
你引入就好了

**Comment by luqaing198855** [comment]
这是你maven仓库没有这4个包
你引  入就好了

**Comment by Samurais** [comment]
参考文档

https://docs.chatopera.com/products/cskefu/engineering.html

设置 maven repo

```
    <repositories>
        <repository>
            <id>chatopera</id>
            <name>Chatopera Inc.</name>
            <url>https://nexus.chatopera.com/repository/maven-public</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
```

该maven服务已经代理主要公共的maven repo如 aliyun, centrel 等
