### ISSUE TITLE
It will be nice if project remove some unused files. 

### ISSUE THREAD

**Issue by DongJigong** [chatopera/cosin#343]
## 原因说明
The git clone costs a long time. this project seems too big.
## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
Sounds like we need a huge rebase work. We would release another big version in 2020, 春松客服 v6. By then, we would approach these rebase operations, thanks.
