### ISSUE TITLE
这个客服系统比基于Odoo的客服系统cs_base强么

### ISSUE THREAD

**Issue by pyrun13** [chatopera/cosin#346]
全球NO1开源架构 Odoo 
相关项目  [https://github.com/JoneXiong/cs_base](https://github.com/JoneXiong/cs_base)
不知道有没有可比性？

**Comment by Thunural** [comment]
我觉得你这种人提这种问题就是讨骂的。

**Comment by Samurais** [comment]
Odoo 的性能很差，在 2013年研究过 Odoo，当时还称为 OpenERP，所以它的优势是ERP，不是客服系统。
