### ISSUE TITLE
改变语言

### ISSUE THREAD

**Issue by mimcomp** [chatopera/cosin#348]
我如何将系统更改为其他语言，例如英语？
和
我可以在带有apache服务器或任何Web服务器的Windows上安装它吗？

# 描述

## 功能

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
暂时不支持；部署方案请使用官方推荐。
