### ISSUE TITLE
[cc]导出联系人 生成的表格里面无信息 

### ISSUE THREAD

**Issue by wq11123** [chatopera/cosin#35]
# 描述
全部联系人 和全部客户选项里，选中需要导出的联系人，点击导出时生成的xls文件名修改为“春松客服联系人”
并且现在导出的表格中都无数据。
## 现在行为
xls表格命名是优客服的。并且表格是空的
## 预期行为
表格名称修改为春松客服联系人，导出的表格里显示选中的联系人信息
# 解决方案

# 环境

* 代码版本:
The commit hash (`git rev-parse HEAD`)

**Comment by xianliwang** [comment]
已修复
