### ISSUE TITLE
ES报错

### ISSUE THREAD

**Issue by 1147033453** [chatopera/cosin#350]
es安装windows版本6.6.2
http://127.0.0.1:9200/
{
  "name" : "OGFQiRe",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "t9o1AA3ATqKZKvA0GTT7bQ",
  "version" : {
    "number" : "6.6.2",
    "build_flavor" : "default",
    "build_type" : "zip",
    "build_hash" : "3bd3e59",
    "build_date" : "2019-03-06T15:16:26.864148Z",
    "build_snapshot" : false,
    "lucene_version" : "7.6.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

application.properties文件：
spring.data.elasticsearch.cluster-name=elasticsearch
spring.data.elasticsearch.cluster-nodes=127.0.0.1:9300
spring.data.elasticsearch.local=false
spring.data.elasticsearch.repositories.enabled=true

报错：
2020-07-31 16:53:02.179 ERROR o.s.d.e.r.s.AbstractElasticsearchRepository - failed to load elasticsearch nodes : org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{127.0.0.1:9300}] [localhost-startStop-1]

**Comment by Samurais** [comment]
不支持该es版本，请参考春松客服依赖。

https://github.com/chatopera/cosin/blob/osc/docker-compose.yml

建议运行春松客服使用官方文档
https://docs.chatopera.com/products/cskefu/deploy.html
