### ISSUE TITLE
关于租户功能的咨询

### ISSUE THREAD

**Issue by PhageT2** [chatopera/cosin#354]
# 描述
目前想部署一套系统，提供给两个部门使用，管理员权限和数据都是隔离的，就是本部门的只能看到本部门的。目前看代码，租户功能应该是支持这些的，但是租户功能应该是没写完吧？cskefu是在代码中固定的

## 功能

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [x] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
我们对多租户的定义是 SaaS服务里，提供不同春松客服实例，数据层面完全隔离，每个租户独立计费，每个租户相当于是不同企业或个人。

您的需求在我们看来不是多租户，而是一个权限 ACL 管理的模式：一个大的组织里，多部部门，还是用一个春松客服实例。

这个需求我们在春松客服商业版里提供。联系参考 [春松客服商业支持](https://docs.chatopera.com/products/cskefu/index.html#%E5%95%86%E4%B8%9A%E6%94%AF%E6%8C%81)。

**Comment by PhageT2** [comment]
ACL管理模式下，不同部门的数据是独立的吗？在开源版本中，如果用户的orgid设置为空，登录后会先去创建一个企业，也能基本满足不同部门数据隔离的需求，但是系统设置是使用的同一条数据

**Comment by Samurais** [comment]
orgi id 就是租户，ACL是同一个租户，但是 ACL 保证了一个租户内有超级管理员，超级管理员可以建立组织，然后创建管理员账号委派到不同组织，这个管理员就可以管理本组织内的资源，组织和组织之间数据隔离。

**Comment by PhageT2** [comment]
MainContext.SYSTEM_ORGI  请问一下程序中这个变量的用途是什么？和租户有什么关系？
