### ISSUE TITLE
nginx怎么配置成非443的https端口，login总是会重定向回443端口

### ISSUE THREAD

**Issue by felixlwang** [chatopera/cosin#357]
# 描述   nginx配置https默认443端口没有问题，但是换成其他端口则会重定向回默认端口

## 现在行为   访问https://kf.xx.com:50901，会被重定向到https://kf.xx.com/login.html。访问https://kf.xx.com:50901/login.html，登陆成功后，会被重定向到https://kf.xx.com。

nginx配置如下：
server {
        listen       50901 ssl;
        server_name  kf.xx.com;
        error_page 497 https://$http_host$request_uri;

        ssl on;
        ssl_certificate /usr/local/ssl/xx_kf.xx.com.pem;
        ssl_certificate_key /usr/local/ssl/xx_kf.xx.com.key;
        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        set $project_name cosin-50901;
        #charset koi8-r;

        client_max_body_size 100M;

        if ($time_iso8601 ~ "(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})") {
                set $time $1$2$3$4;
        }

        access_log /home/prod/log/$project_name/$project_name-access-$time.log custom_format;

        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_pass http://0.0.0.0:8035;
        }

        location /socket.io {
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_http_version 1.1;
                proxy_pass http://0.0.0.0:8036;
        }
}

## 预期行为   可以用https://kf.xx.com:50901正常访问，不会被重定向到https://kf.xx.com

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by kylezhang** [comment]
请按照issue模版。
