### ISSUE TITLE
[cc] 坐席在线状态，连续刷新两遍就掉线 

### ISSUE THREAD

**Issue by wq11123** [chatopera/cosin#36]
# 描述
坐席在线状态，连续刷新两遍就掉线
## 预期行为
保持在线状态或者手动更改状态
# 解决方案

# 环境

* 代码版本:
The commit hash (`git rev-parse HEAD`)

**Comment by 96298li** [comment]
页面加载完成后，前端判断进行处理
![image](https://user-images.githubusercontent.com/54433238/63669495-c4e4c300-c80c-11e9-9e82-2fcb1a41f9c4.png)
![image](https://user-images.githubusercontent.com/54433238/63669599-06756e00-c80d-11e9-9e0f-7b011dd3b464.png)

**Comment by xianliwang** [comment]
已解决
