### ISSUE TITLE
知识库快捷bug

### ISSUE THREAD

**Issue by hello-sly** [chatopera/cosin#361]
# 描述
在使用春松客服后台，知识库快捷，答案是undefined。机器人使用时，知识库答案是有的。

## 预期行为

# 解决方案

# 环境
按照官方应用部署文档，docker部署的
## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [  ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
@hello-sly 请帮忙添加截图，感谢！

**Comment by hello-sly** [comment]
![image](https://user-images.githubusercontent.com/65380368/94089426-c20c3580-fe45-11ea-8364-c3ea5817ec54.png)
截图已添加。
