### ISSUE TITLE
sample.env在部署中起什么作用

### ISSUE THREAD

**Issue by manToHome** [chatopera/cosin#371]
# 描述

## 功能

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
春松客服部署建议使用 docker-compose, 我们提供了 docker-compose.yml 完成基于 docker 的一键部署和运维，.env 是目前业界广泛支持的环境变量声明文件，docker-compose也支持该约定，参考：https://docs.docker.com/compose/environment-variables/

所以，.env 文件可以用来覆盖 docker-compose 中的变量。

参考阅读：
https://www.cnblogs.com/sparkdev/p/9826520.html

春松客服使用 Docker，基础知识参考更多 docker 文档。
