### ISSUE TITLE
[cc] 坐席工作台-服务小结点击立即提交没反应，会话历史-服务小结有数据

### ISSUE THREAD

**Issue by wq11123** [chatopera/cosin#46]
# 描述
坐席工作台-服务小结多次点击立即提交没反应，但是会话历史-服务小结有多次点击的数据
## 现在行为
 
![bc93c5914e5ea11e505fe61cf678512](https://user-images.githubusercontent.com/40993206/45006089-c29cbe00-b029-11e8-8b4b-49f9d94820a5.png)
![6be33878c322071391ffcecc751f2e2](https://user-images.githubusercontent.com/40993206/45006151-11e2ee80-b02a-11e8-83a4-056bdef75e99.png)

## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
duplicated with #107

**Comment by almerzht** [comment]
服务类型数据是配置了数据字典才出来的吗？
