### ISSUE TITLE
机器人客服有支持吗？

### ISSUE THREAD

**Issue by shibing624** [chatopera/cosin#50]
# 描述

## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
机器人客服是通过[多轮对话设计器](https://docs.chatopera.com/conversation-designer.html)和[智能问答引擎](https://docs.chatopera.com/chatbot-engine.html)来支持的。我们提供制作聊天机器人的工具、培训和定制开发服务。

另外，语音识别的模型也正在做。
