### ISSUE TITLE
[cc]全部联系人/全部客户，新建/编辑电话号码，字段限制

### ISSUE THREAD

**Issue by wq11123** [chatopera/cosin#6]
# 描述

## 现在行为

![](https://user-images.githubusercontent.com/40993206/44944557-b76c4700-ae0b-11e8-81fe-9172443c4577.png)

## 预期行为

# 解决方案

# 环境

* 代码版本:
The commit hash (`git rev-parse HEAD`)

**Comment by xianliwang** [comment]
@Samurais 企业版没有这个问题

**Comment by xianliwang** [comment]
考虑客户所在地区不同，各地号码规则有差异，所以不进行手机号码字段限制
