### ISSUE TITLE
[cc] 机器人管理页面设计

### ISSUE THREAD

**Issue by Samurais** [chatopera/cosin#68]
# 描述

## parent #63 

# 解决方案
![default](https://user-images.githubusercontent.com/40993206/45290129-63efac80-b521-11e8-84fc-890f839880a2.png)
![default](https://user-images.githubusercontent.com/40993206/45290130-63efac80-b521-11e8-9f90-46f8f68eb105.png)
![default](https://user-images.githubusercontent.com/40993206/45290131-63efac80-b521-11e8-9646-374bb85db1cc.png)

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by wq11123** [comment]
![default](https://user-images.githubusercontent.com/40993206/45989760-92d45980-c0af-11e8-92c2-689cb81fd35d.png)
![default](https://user-images.githubusercontent.com/40993206/45989761-936cf000-c0af-11e8-96cc-932e1a4d2615.png)
