### ISSUE TITLE
[cc]全部联系人/全部客户，新建/删除后会跳到其设定的类型选项页面 

### ISSUE THREAD

**Issue by wq11123** [chatopera/cosin#7]
# 描述
全部联系人/全部客户，新建/删除后会跳到其设定的类型选项页面
## 预期行为
在当前页面操作后就返回到当前页面
# 解决方案

# 环境

* 代码版本:
The commit hash (`git rev-parse HEAD`)

**Comment by xianliwang** [comment]
设计如此
