### ISSUE TITLE
[cc]历史会话-右上按时间搜索，开始时间晚于结束时间，也能搜索

### ISSUE THREAD

**Issue by wq11123** [chatopera/cosin#8]
# 描述
历史会话-右上按时间搜索，开始时间晚于结束时间，也能搜索，并且没有提示

![](https://user-images.githubusercontent.com/40993206/44891189-8d822a00-ad10-11e8-9a0c-750721cbf6ed.png)

## 预期行为

# 解决方案

# 环境

* 代码版本:
The commit hash (`git rev-parse HEAD`)

**Comment by xianliwang** [comment]
5.0版本发布后，时间范围进行限制，不能选择大于当前的时间
