### ISSUE TITLE
[cc] 移动端 聊天昵称显示异常

### ISSUE THREAD

**Issue by mukaiu** [chatopera/cosin#88]
# 描述

![image](https://user-images.githubusercontent.com/7746790/46001485-f7a6a880-c0dd-11e8-8442-57596bc94421.png)

## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
# 移动端智能坐席凌乱
![image](https://user-images.githubusercontent.com/3538629/47070381-a2187400-d223-11e8-8011-6245b5106a1c.png)

**Comment by Samurais** [comment]
已更新

![image](https://user-images.githubusercontent.com/3538629/47080620-190d3700-d23b-11e8-954c-2102c980d26d.png)
