### ISSUE TITLE
[cc] 本地测试在线客服客户端报异常

### ISSUE THREAD

**Issue by hlwomoayiqd** [chatopera/cosin#89]
# 描述
![image](https://user-images.githubusercontent.com/20021746/46059573-6a715b80-c192-11e8-920b-9ea1471ead6d.png)
配置本地127.0.0.1
## 现在行为
![image](https://user-images.githubusercontent.com/20021746/46059640-a5738f00-c192-11e8-8388-b53737b0a326.png)

## 预期行为
正常显示
# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
这个问题是没有识别file://协议，在浏览器打开本地的html文件会发生，正常上线的web服务不会发生这个问题，一个快速的解决方案是，将这个html放在http server上，作为静态资源。然后从浏览器访问该文件的URL，就可以解决。

在代码中，我们需要识别file://协议，但是不好确定用http还是https。
