### ISSUE TITLE
[cc]历史会话-右上搜索一栏，按服务坐席/技能组搜索后，方框内空白

### ISSUE THREAD

**Issue by wq11123** [chatopera/cosin#9]
# 描述
1、历史会话-右上搜索一栏，按服务坐席/技能组搜索后，方框内空白
2、搜索框内“请选择”这三个字不作为选项，从下拉列表中去掉。

![](https://user-images.githubusercontent.com/40993206/44890752-632f6d00-ad0e-11e8-8a9e-c60a49cf959e.png)

## 预期行为

# 解决方案

# 环境

* 代码版本:
The commit hash (`git rev-parse HEAD`)

**Comment by xianliwang** [comment]
设计如此
