### ISSUE TITLE
手机浏览器无法正常访问客服

### ISSUE THREAD

**Issue by xlzuijia** [chatopera/cosin#96]
# 描述
本地测试  weiIm 聊天电脑 谷歌 正常显示 用安卓 手机测试 uc QQ 微信 手机浏览器访问 失败
访问路径 http://192.168.43.102:8080/layuissm/cos-client.html
客服  项目是 走的 内置tomcat 
 cos-client.html 走的tomcat 9.0  layuissm 项目
![error05](https://user-images.githubusercontent.com/23306916/46274652-c0784180-c58c-11e8-8a53-01cf0dc4915a.png)

## 现在行为

![errot60](https://user-images.githubusercontent.com/23306916/46274553-71caa780-c58c-11e8-936a-9698d3bbf5e2.png)

## 预期行为
![error5](https://user-images.githubusercontent.com/23306916/46274565-7abb7900-c58c-11e8-8cb0-afd05150fef6.png)

# 解决方案
还在读源码想办法中
# 环境
window 7 64  eclipse  tomcat 9.0 , 手机 安卓 红米note5  miui9.5
* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
http://localhost:8035是用于在开发机器上测试，如果是手机访问，需要使用
http://IP:8035/im/渠道ID.html 进行访问。

你如上图代码加载到手机上，是访问手机的localhost地址了，不可能访问到。

@xlzuijia

**Comment by xlzuijia** [comment]
谢谢
